### ISSUE TITLE
Update screenshots 

### ISSUE THREAD

**Issue by Aga-C** [ManeraKai/simplytranslate-flutter-client#106]
Hi,

If the new looks of the app are ready, it would be good to update screenshots in F-Droid metadata and GitHub README.

**Comment by Valdnet** [comment]
As for me, you can, and even 😁.

**Comment by ManeraKai** [comment]
How is it now?

**Comment by Valdnet** [comment]
Yes. You can add screenshots of the new look of the application.

**Comment by Aga-C** [comment]
@ManeraKai I see minor issue in settings look. Please wait, I'll do a pull request in few minutes, and you can update then the screenshots.

**Comment by Aga-C** [comment]
@ManeraKai You can check: #108

**Comment by Aga-C** [comment]
Now it's perfect 👍

**Comment by Valdnet** [comment]
@ManeraKai Add a description for:

> About
> No description, website, or topics provided.

e.g. this one:

> An unofficial mobile client that connects to multiple SimplyTranslate instances.


I am not permission to do so 😉.

**Comment by Valdnet** [comment]
But I mean GitHub. Here:

![obraz](https://user-images.githubusercontent.com/47037905/135048544-65f81d55-6e5a-420f-92b9-af88118d44a2.png)

**Comment by ManeraKai** [comment]
oh, I thought you meant the about page in the app. ok 👍

**Comment by ManeraKai** [comment]
I don't have a website for it though. Added about and some topic tags

**Comment by Valdnet** [comment]
> I don't have a website for it though.

If you want, I can take care of it. I can set up a website for the application 😜.

**Comment by ManeraKai** [comment]
If you want to set up a website, best idea to put it here in GitHub pages.

**Comment by Valdnet** [comment]
I was rather thinking about setting up a website on my own server. I have a server 😉.

**Comment by ManeraKai** [comment]
I have a server too but the electricity cuts off sometimes, but why a server if it will be just some client side information. No server side code would be there?

**Comment by Valdnet** [comment]
> No server side code would be there?

Not. The code is not placed, only a link to it.

Professionally, it is done like this:

An official website for the application is assumed.
Description, screenshots, author etc. are included
Links to the license and source code (GitHub) are posted.
Link to download the application (additionally it can be placed on the website, but this is only an option).
Contact for support (can be Issue GitHub).

**Comment by ManeraKai** [comment]
like this: https://qtox.github.io/

> Not. The code is not placed, only a link to it.

?

**Comment by Valdnet** [comment]
> like this: https://qtox.github.io/

More or less this is what it is all about 😁.

> Not. The code is not placed, only a link to it.
> 
> ?

Link to the GitHub repository.


I can do it on a subdomain (the domain is short, only it is pl.) Or I can buy a domain (but it's to be agreed what and then it needs to be maintained). The server is hosted, so don't worry about powering it up.

But that's just a suggestion. Nothing by force.

Think it over.

**Comment by ManeraKai** [comment]
I don't have a problem if you'll se It up on a different domain than GitHub pages. It's a minor thing.
However, I can't maintain another code repo as I don't have time for maintaining this app and studying. If you'll maintain the site, that would be nice. I may help but not that frequent.

**Comment by Valdnet** [comment]
> If you'll maintain the site, that would be nice.

I can take care of it (server, installation, artwork, etc.).

> I may help but not that frequent.

Relax 😁. I can take care of everything 😉.
