### ISSUE TITLE
Add a "Paste" icon

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#11]
1. I suggest adding a "Paste" icon for the translated text. This will speed up and simplify when pasting text for translation. Currently, you need to hold your finger on the text window to select paste text.

2. I suggest placing the "Paste" icon and moving the "Copy" icon and the "Translate" button according to the screenshot below.
3. Add an icon for the application menu (as it probably will menu 😁).

![obraz](https://user-images.githubusercontent.com/47037905/133428168-f0a5efd4-83d9-428e-aa39-643b14801adc.png)

App:
Simply Translate v1.0.0

**Comment by ManeraKai** [comment]
>     3. Add an icon for the application menu (as it probably will menu 😁).
Is it for the instance selector?

**Comment by Valdnet** [comment]
> Is it for the instance selector?

Menu for the application, which will contain info about the application, settings, licenses, etc.

**Comment by ManeraKai** [comment]
> Menu for the application, which will contain info about the application, settings, licenses, etc.

This will be discussed here: #25
