### ISSUE TITLE
Change to-language of default sharing

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#114]
Steps:

1. Select application settings.
2. Change the default to-language of the share to a different one.
3. Exit the settings.

The windows in the application are not displayed.

![obraz](https://user-images.githubusercontent.com/47037905/135797599-3e47a89a-9b0f-44c0-9777-cff0a15ad1bf.png)

Apps:
Android 10
Simply Translate 1.1.0

**Comment by ManeraKai** [comment]
This doesn't happen to me.

**Comment by ManeraKai** [comment]
Happens when UI's language is in another language than English.

**Comment by Valdnet** [comment]
> Happens when UI's language is in another language than English.

Exactly.

**Comment by ManeraKai** [comment]
This only happens when you press the option instead of `Enter`. The functions are a bit different. Each one puts a different data on cookies where it should be the same.
