### ISSUE TITLE
App language default to Arabic if system language has no translation

### ISSUE THREAD

**Issue by romainreignier** [ManeraKai/simplytranslate-flutter-client#115]
I have installed the 1.1.0 version from F-Droid, my system is language is French and SimplyTranslate opens in Arabic.

**Comment by ManeraKai** [comment]
You mean the UI or the select language button options?

**Comment by romainreignier** [comment]
The UI

**Comment by ManeraKai** [comment]
Do you have the second language as Arabic in your system?

**Comment by romainreignier** [comment]
I don't think so but I will check.

**Comment by romainreignier** [comment]
No, only French

**Comment by romainreignier** [comment]
![Screenshot_20211004-093208_Settings](https://user-images.githubusercontent.com/8845664/135811027-09dc1034-7378-4e77-921b-37b08b4f9a3e.jpg)

**Comment by ManeraKai** [comment]
Try it in this apk: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1302666356

**Comment by romainreignier** [comment]
It works, the UI is now in English.
Thank you for your reactivity.
I think a new release should be made on F-Droid to fix the issue before too much people complain.

**Comment by ManeraKai** [comment]
> I think a new release should be made on F-Droid to fix the issue before too much people complain.

We will add this in version `1.1.1`. Problem is that F-Droid is a small team. Version `1.1.0` took almost 7 days to be published after publishing the release from my side.

**Comment by ManeraKai** [comment]
Note: your apk will be slow as it's in debug mode. If you want it in release mode, you'll get some errors because of signing keys.

**Comment by romainreignier** [comment]
> Note: your `.apk` will be slow as it's in debug mode. If you want it in release mode, you'll get some errors because of signing keys.

Yes I have noticed it is a debug build, but it is not an issue for me.

**Comment by ManeraKai** [comment]
@romainreignier just to be informed. The `.apk` I gave you turned out to not translate the UI to other languages. It just default to english even if there's a translation for the system's language. That is now fixed though.
