### ISSUE TITLE
License logo on website is LGPL

### ISSUE THREAD

**Issue by romainreignier** [ManeraKai/simplytranslate-flutter-client#116]
It is stated on Github that SimplyTranslate is under the GPL v3 license but on the website, the **L**GPL logo is shown.

**Comment by Valdnet** [comment]
I'll change the logo 😉.

**Comment by Valdnet** [comment]
Changed. Green was more suited to the page 😁.
Is she good now?

**Comment by ManeraKai** [comment]
> Green was more suited to the page

Third party images don't have to match with the sites theme.

She's good now. I don't know why `she` though.
