### ISSUE TITLE
Text string "OK"

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#12]
Please change the following text string "ok" to uppercase. Correctly this is "OK".

https://github.com/ManeraKai/simplytranslate-flutter-client/blob/763f1c47c577875cc6b9b6fa71f2a6bb885b910b/lang/main_en.arb#L122

**Comment by ManeraKai** [comment]
You mean like this?

**Comment by Valdnet** [comment]
> You mean like this?

Yes. Now is good 👍.
