### ISSUE TITLE
Change text string in app settings

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#139]
Please change the text string below to make it more understandable for application users and translators. It is hardly understandable in its present form.

https://github.com/ManeraKai/simplytranslate_mobile/blob/076d7b35c1befdd130b5a105eab58b889baba7fd/lang/main_en.arb#L155

**Comment by ManeraKai** [comment]
More squeezing: `Determines the translation language for shared text from another app.`?

**Comment by Valdnet** [comment]
`Determines the translation language for shared text from another app.`

Cool 👍.

**Comment by CafeTango** [comment]
Good morning!

If you don't mind, may I pass you the translations by email instead of doing
it on Github? I am not a technical person and I find Github daunting.
Sorry.

Would you consider adding the project to Transifex or other translation
clients?  These are easier for us non-techies to navigate ^_^
 
Have a nice weekend!

Cha

  _____

**Comment by Valdnet** [comment]
> Would you consider adding the project to Transifex or other translation clients?

I considered adding text strings for some client but I don't know if they are suitably adapted.

@ManeraKai what do you think?

@CafeTango I sent you a message in Transifex :wink:.

**Comment by ManeraKai** [comment]
@CafeTango thre is no problem at all with that. You can send it via email. I've mentioned that part in the readme too.

Yeah I may think of adding it to transifex, why not?!

**Comment by Valdnet** [comment]
> Btw, I have several apps hosted in POEditor (all are OOS).

I will translate a little in my free time 😉.

**Comment by ManeraKai** [comment]
I'll close this issue as I'll get notified of new translations on POEditor.
