### ISSUE TITLE
Lock selection of same language

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#14]
I propose to block the choice of the same language for translation. Even though the program can handle the translation from one language to the same language, it seems a bit strange to the user.

Two options for selecting changes in the application:

1. Text string dimmed with same language selection.
2. Text string with same language selection is not displayed.

![obraz](https://user-images.githubusercontent.com/47037905/133442554-2400f9ca-99dc-4083-a663-874f8e3b1555.png)

App:
Simply Translate v1.0.0

**Comment by ManeraKai** [comment]
I chose the first one. Now it's dimmed and unselectable. If you press on the submit button (Enter Key), it will choose the next one on the list.

**Comment by Valdnet** [comment]
Cool. I am looking forward to the test version 😉.

**Comment by Valdnet** [comment]
No gray for the same language in light and dark theme.

![obraz](https://user-images.githubusercontent.com/47037905/134711297-1410ce88-28fd-448b-a448-a8a3a4f0a94f.png)

![obraz](https://user-images.githubusercontent.com/47037905/134711377-155f3c8b-b40a-40ea-84d8-ce73ee91604a.png)

**Comment by Valdnet** [comment]
No gray for the same language in light and dark theme.

![obraz](https://user-images.githubusercontent.com/47037905/134711297-1410ce88-28fd-448b-a448-a8a3a4f0a94f.png)

![obraz](https://user-images.githubusercontent.com/47037905/134711377-155f3c8b-b40a-40ea-84d8-ce73ee91604a.png)

**Comment by ManeraKai** [comment]
Fixed.
