### ISSUE TITLE
Simply Translate web extension

### ISSUE THREAD

**Issue by anedroid** [ManeraKai/simplytranslate-flutter-client#149]
What about making a browser extension for privately translating web pages such as https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/?

**Comment by ManeraKai** [comment]
I deleted the repo as there are ready extensions for translation. They just need to use our SimplyTranslate servers rather than google's: https://github.com/FilipePS/Traduzir-paginas-web
