### ISSUE TITLE
Thickness of border line

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#16]
I suggest to try to reduce the thickness of the border line for all windows. Currently, the program window looks too square and massive.

App:
Simply Translate v1.0.0

**Comment by ManeraKai** [comment]
I've made it that way to be the same as the [web client](translate.metalune.xyz/) to make it more familiar to users.

**Comment by Valdnet** [comment]
I understand, but don't follow this pattern. I think a thinner line will improve the appearance of the application 😉.

**Comment by ManeraKai** [comment]
Can you send me a screenshot of how it appears on your phone, because it's just 2 pixels width.

It looks like this on my emulator:
<img width=360 src="https://user-images.githubusercontent.com/40805353/133476766-f940ea2f-c0ca-4063-b21e-24cbd5baf3bc.png">

**Comment by Valdnet** [comment]
It looks the same for me. Too thick lines in my opinion. Please change to 1px and try what it looks like. Send a screenshot 😉.

**Comment by ManeraKai** [comment]
<img width=360 src="https://user-images.githubusercontent.com/40805353/133478420-97b664a0-18ab-482b-a599-0a0d397b775f.png">

**Comment by Valdnet** [comment]
This is it. The application became prettier and more delicate right away. I would have left it that way.

**Comment by Valdnet** [comment]
For the sake of sample, you can slightly round the corners of the frame, but only slightly so that they are not so angular.

**Comment by ManeraKai** [comment]
<img width=360 src="https://user-images.githubusercontent.com/40805353/133479560-dfe77417-0d65-439f-8a8d-2ea05ab092a2.png">

**Comment by Valdnet** [comment]
I think it can stay that way. It's good for me 👍.

**Comment by ManeraKai** [comment]
Different personalities.

**Comment by Valdnet** [comment]
Remember to round the corners 😉.

**Comment by Valdnet** [comment]
Issue can be closed.
All issues are discussed in this issue: #33.
