### ISSUE TITLE
Add a "Delete" icon

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#17]
I propose to add icons to delete text for both windows. This will allow you to quickly remove the text from the window with the original text to be translated. The icon should only be active when there is text in it.
However, in the window with text already translated into another language, it will allow you to delete the current translated text. Of course, it also has to be active only when the translated text appears.
Currently, this is missing, because after changing the original text and pressing "Translate", the user is not sure if the changes have been made to the translation. Only cleaning the window makes him practically sure that it is a new translated text.

**Comment by ManeraKai** [comment]
Now it will be active if there is a `translation_input` or a `translation_output`. Will delete both of them if pressed.
