### ISSUE TITLE
Add a "Copy" icon

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#18]
I suggest adding a "Copy" icon in the window for the original text to be translated. It should be active only when there is content in it. This will allow the original text to be copied after the user has added changes.

**Comment by ManeraKai** [comment]
I don't think there will be frequent use cases for it as the other two buttons. The user though can still copy text with the toolbar options. Adding it will add an extra thing on screen. **Simply** Translate shouldn't be bloated.

**Comment by Valdnet** [comment]
In my opinion you are wrong. Sometimes the translator has to substitute a word for the original text to make sense of the sentence. In my case, I do it quite often.

I will summarize all the necessary functions and publish in a new issue for visual evaluation 😉.

**Comment by ManeraKai** [comment]
?
![image](https://user-images.githubusercontent.com/40805353/133565324-da9d57f2-76c4-45fb-8471-f080babba372.png)

**Comment by Valdnet** [comment]
Do you not want to introduce the interaction of the icons described in Issue #22.
The white icon will blend in with the text.

**Comment by ManeraKai** [comment]
> Do you not want to introduce the interaction of the icons described in Issue #22.
I'm adding them one by one for every issue.

> The white icon will blend in with the text.
The icons have a separate column for them, the text will wrap before reaching them.

**Comment by Valdnet** [comment]
> The icons have a separate column for them, the text will wrap before reaching them.

This is my guess that the text will be wrapped 😉. But we will see in the finished test version how it will look like.
