### ISSUE TITLE
Add a scroll bar

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#19]
I propose to add a scroll bar in the windows for text for longer text.
Example:

![obraz](https://user-images.githubusercontent.com/47037905/133481779-3a764135-56c2-480a-a0c4-bfcb39939eb4.png)

**Comment by ManeraKai** [comment]
Note: it's not pretty now. The pretty problem will be fixed here #24

**Comment by Valdnet** [comment]
In this [test version](https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1260837152), the scroll bar with long text is not displayed again.

![obraz](https://user-images.githubusercontent.com/47037905/134328080-41747e15-59c6-4b38-8fb7-8fd7871003ec.png)
