### ISSUE TITLE
App appearance and function interactivity

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#22]
Summary of all app features and appearance:

1. Move the "Translate" button to the right side of the application.
Issue: #11.

![obraz](https://user-images.githubusercontent.com/47037905/133559716-372c5cdd-9d01-4431-97f7-c14b6bd8e673.png)

2. Add the "Paste" icon for the original text to translate window.
Issue: #11.

- No text to translate

![obraz](https://user-images.githubusercontent.com/47037905/133559658-3bdf2689-b596-4514-b2dc-5be1311942bd.png)

3. Add the "Delete" icon to the two windows and move the "Copy" icon to the translated text window.
The "Paste" icon changes to the "Delete" icon.
Issue: #11.
Issue: #15.
Issue: #17.
Issue: #18.
- The typed text to be translated.

![obraz](https://user-images.githubusercontent.com/47037905/133561867-571ea996-e23a-4f7e-9b09-c629b780020d.png)

- After translating the text

![obraz](https://user-images.githubusercontent.com/47037905/133562896-65a055be-60b6-45bb-8b4d-c399b28c0d6f.png)

- After deleting the text for translation, the "Paste" icon reappears

![obraz](https://user-images.githubusercontent.com/47037905/133564997-0fe016cc-58c9-4382-b188-0a2578a16b7b.png)

These are just my suggestions. I know that it takes some time, but in my opinion, these are the basic functions of the program that will make it easier for the user to use it and enrich the program with a function.

**Comment by ManeraKai** [comment]
I prefer having them grey as to having them disappear. The interactions will be the same though.

> After deleting the text for translation, the "Paste" icon reappears

There will be users who want to paste twice. It'll be just gray if it was disabled. So it won't add much clutter if kept enabled.

**Comment by Valdnet** [comment]
Well. We will see it in full in the test version how they will function 😉.

**Comment by Aga-C** [comment]
As I noticed, delete and copy buttons are disabled after pasting text with the paste button or from another app. And probably the paste button is always enabled even if there is no value in the clipboard. Generally, there should be some conditions on the buttons, depends on if there is some text in the field.

**Comment by Valdnet** [comment]
>  It'll be just gray

@Aga-C The developer says they will be gray (inactive).

BTW: @Aga-C As I wrote before, but I will write again that you translate programs very well 🥇. Or maybe you want to help the Polish translators in the [Nextcloud Server team](https://www.transifex.com/nextcloud/teams/). I am a reviewer there. It would be nice to see you there.

**Comment by Aga-C** [comment]
> @Aga-C The developer says they will be gray (inactive).

I mean the issue, that for now these buttons don't work correctly in all conditions (I've tested the app for a while some time ago with current new functionalities).

> BTW: @Aga-C As I wrote before, but I will write again that you translate programs very well 🥇. Or maybe you want to help the Polish translators in the Nextcloud Server team. I am a reviewer there. It would be nice to see you there.

Thanks for this, but I stay with the apps that I use. Besides translating, I also like to improve these apps by fixing/adding features. And that's all. I don't like spending a lot of time on this each day 🙂 

And I thank you with helping to improve open source apps - your testing skills are excellent!

**Comment by Valdnet** [comment]
> I mean the issue, that for now these buttons don't work correctly in all conditions (I've tested the app for a while some time ago with current new functionalities).
@ManeraKai How does it work for you now?

@Aga-C Understands 😉.

> And I thank you with helping to improve open source apps

And the same 😉.

> your testing skills are excellent!

Thanks 😁.

**Comment by ManeraKai** [comment]
> @ManeraKai How does it work for you now?

@Aga-C is right bout that. This only happens when the app is in the background. If you shut it down and then paste from another app, it'll work fine.
