### ISSUE TITLE
Add about

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#23]
I propose to add "About" in the application menu, which should contain:

1. Developer information.
2. Application version number.
3. Information on copyright and related rights (right to application icons).
4. Information about the co-authors.
5. Information about translating the application.
E.t.c.

Some information can be extracted in a separate application menu, e.g .:
- About
- License
- Version

In general, the application in version 1.0 should not be released without providing the author, license and related rights.

**Comment by ManeraKai** [comment]
>1.Developer information

What should be written in it?

**Comment by Valdnet** [comment]
Who created the application 😉.

**Comment by ManeraKai** [comment]
what personal information should I add other than the name?

**Comment by Valdnet** [comment]
First and last name are enough.

**Comment by ManeraKai** [comment]
Added content to it: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1274237092

**Comment by Valdnet** [comment]
Interesting approach for "About".

@Aga-C  What do you think?

**Comment by Aga-C** [comment]
Looks really great! 🚀

**Comment by Valdnet** [comment]
Accepted :wink:.
@Aga-C Will you deal with the translation?

**Comment by Aga-C** [comment]
@Valdnet Ok, I will do it later today.

**Comment by ManeraKai** [comment]
Should this issue be closed now?
