### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#26]
I noticed that you are using the SimplyTranslate icon for the mobile app icon. I understand that your suggestion is that this is a SimplyTranslate mobile client.
In formal terms, I would arrange it with the [icon's author](https://joelchrono12.ml/) to use it in your application, if you haven't already done so. Of course, this information about its author should be provided in "About" the application about its author.

In general, I would change it to my own, more aesthetic and more pleasant in colors. Remember that the future user first judges by the application icon when searching for the application, and then by the screenshots. The app may be cool, well-functioning, but if he doesn't like the app icon, he may not download and install it at all.

**Comment by ManeraKai** [comment]
1.I took permission from him:
![image](https://user-images.githubusercontent.com/40805353/133601351-6dd65e06-a643-470f-9de5-db6c2e1d9789.png)
2. Yeah, your right. the author will be also in the README.
3. I'm not a Graphic Designer but we'll see about that.

**Comment by Valdnet** [comment]
Cool 👍. In that case, I'm closing the issue.

**Comment by Valdnet** [comment]
@ManeraKai Give me your email address. If you can, I want to send you something 😉.

**Comment by ManeraKai** [comment]
manerakai@protonmail.com

**Comment by ManeraKai** [comment]
**Note**: I've contacted metalune with a different email address. I've contacted him with: hazem_almaleeh1@hotmail.com

**Comment by Valdnet** [comment]
I sent :gift:.
