### ISSUE TITLE
Narrow the window boxes

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#28]
I suggest you narrow down the windows for:

1. Choice of languages.
2. "Translate" button.
3. Server selection window.

Examples:
The screenshots already contain a border for the "Translate" button from issue #27.

![obraz](https://user-images.githubusercontent.com/47037905/133608408-d44e2ace-6bb6-41fe-b4cf-3271ead95027.png)
![obraz](https://user-images.githubusercontent.com/47037905/133608436-0e4e3fdc-0516-415d-9f82-87fd0376c490.png)
![obraz](https://user-images.githubusercontent.com/47037905/133608460-4536a64e-b570-4939-8af5-1e11f954be14.png)

For comparison:

![obraz](https://user-images.githubusercontent.com/47037905/133609553-a44fcf2a-2f44-40cc-a01a-fdc0e7788fa9.png) ![obraz](https://user-images.githubusercontent.com/47037905/133608379-c50dd220-92fa-4436-b1df-aa5ee47b2688.png)

**Comment by ManeraKai** [comment]
Narrowed them down. Resized the text a little bit:
<img width=360 src="https://user-images.githubusercontent.com/40805353/133686170-42b00920-64fc-4565-bc67-2fe00ce3f72f.png">

**Comment by Valdnet** [comment]
This is still missing: #16.
