### ISSUE TITLE
Correct text strings

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#29]
Please correct the spelling for English in the text strings:
https://github.com/ManeraKai/simplytranslate-flutter-client/blob/be79ac446a4cf4b04e01674c8b0ac8ff40a582fd/lang/main_en.arb#L117
Correct: `Enter text here`

https://github.com/ManeraKai/simplytranslate-flutter-client/blob/be79ac446a4cf4b04e01674c8b0ac8ff40a582fd/lang/main_en.arb#L121
Correct: `Check instance`

https://github.com/ManeraKai/simplytranslate-flutter-client/blob/be79ac446a4cf4b04e01674c8b0ac8ff40a582fd/lang/main_en.arb#L122
Correct:  `No internet connection`

**Comment by ManeraKai** [comment]
I'm working on the code right now. Can you please open a pull request for it.

**Comment by Valdnet** [comment]
Done 😉.
