### ISSUE TITLE
Add possibility to translate the app

### ISSUE THREAD

**Issue by Aga-C** [ManeraKai/simplytranslate-flutter-client#3]
Hi,

Thanks for this great app! 
I think that for the translator app, it would be vital to have UI in user language. Could you separate strings to a separate file, so we would be able to translate the app to other languages?

**Comment by ManeraKai** [comment]
Thanks for your suggestion.
I've created a [`lang`](https://github.com/ManeraKai/simplytranslate-flutter-client/tree/main/lang) directory, and translation files will be there. You can use the [`en_main.arb`](https://github.com/ManeraKai/simplytranslate-flutter-client/blob/main/lang/main_en.arb) file as a template.
I haven't touched anything related to language direction yet. But I'll do it when I finish translating the app to my `rtl` language **(Arabic)**.

**Comment by Aga-C** [comment]
Thanks for adding an arb file. I've found that some strings are missing in this file:
- Enter Text Here
- copied to clipboard
- Random
- Custom
- Check
- Cut
- Copy
- Select all
- Paste

**Comment by Aga-C** [comment]
What about strings like "Cut", "Copy", "Paste" and "Select all"? Is it possible to translate them?

**Comment by ManeraKai** [comment]
They will be translated automatically once you add your language file.
Here I've added a dump template for arabic and named it `main_ar.arb`. Run `flutter gen-l10n` for converting translation files from `.arb` to `.dart`. more about that here: https://phrase.com/blog/posts/flutter-localization/
The system text selection tools then changed automatically to arabic.
![image](https://user-images.githubusercontent.com/40805353/133128156-edecf38e-62c8-469c-acdf-b1bcd18f1707.png)

**Comment by Aga-C** [comment]
I've managed to run the app in emulator, and "Enter Text Here" placeholder is not in the file to translate.

**Comment by ManeraKai** [comment]
You're right. Added it now.

**Comment by Valdnet** [comment]
And it wouldn't be better to add the translations right away in "strings.xml" in the "Values" directory. Just like it is in other applications.

@Aga-C It's good that you also translate the application here, because it seems that it will be a good application 😁.

**Comment by ManeraKai** [comment]
I've left it open because I didn't touch the `rtl` problem yet, but it's up to you.

**Comment by Valdnet** [comment]
@Aga-C Please open an issue 😉.

**Comment by Aga-C** [comment]
Sorry, I thought it's already done 😅

**Comment by ManeraKai** [comment]
> @ManeraKai And it wouldn't be better to add the translations right away in "strings.xml" in the "Values" directory. Just like it is in other applications.
> 
> @Aga-C It's good that you also translate the application here, because it seems that it will be a good application grin.

I did it like that as it's the standard way of translating apps in Flutter.

**Comment by Aga-C** [comment]
>@Aga-C It's good that you also translate the application here, because it seems that it will be a good application 😁.

@Valdnet That's the translator app I was looking for (open source and without tracking), that's why I want to support it to make it perfect :-)

**Comment by Valdnet** [comment]
@Aga-C Same as me. I was looking for a variety of apps that could help with the translation, but no good and ad-free.

@ManeraKai You already have Polish language translators and application testers. Now you just need to write code well and quickly and make changes fairly quickly. Only in this way can you achieve success with the application.

So far, all the applications tested by zemnie quickly reached a large number of users. I think it will be also in this case. We count on you :wink:.

**Comment by ManeraKai** [comment]
**Note:** I didn't translate the F-Droid part yet. This issue was still open because of the `rtl` problem. Will be closed as it's fixed now.
