### ISSUE TITLE
Add a tab navigation for different engines

### ISSUE THREAD

**Issue by Aga-C** [ManeraKai/simplytranslate-flutter-client#31]
Hi,

I think that it would look better if separate translation engines would be chosen not on a bottom of the page, but at the top. The best in my opinion would be a tab navigation, something like here: <https://blog.logrocket.com/flutter-tabbar-a-complete-tutorial-with-examples/>. Something similar is also in a web client.

It would be good not only from UX view, but also you can narrow functionalities. For example, LibreTranslate doesn't support as many languages as Google Translate, so you can do language filtering for the proper page.

**Comment by ManeraKai** [comment]
1. Do you prefer this approach, or having an app menu and a separate settings page. Because we're gonna make an about page for this issue #23.
2. For filtering supported languages, I totally forgot about that.

**Comment by Aga-C** [comment]
I prefer this approach - GoogleTranslate and LibreTranslate in separate tabs. And the option to set an instance could be available in settings from the app menu.

**Comment by ManeraKai** [comment]
I've added now tabs for Google and Libre. Libre won't be available if it's not supported on instance. FromLang, ToLang, and TranslationInput have the same values on both tabs, TranslationOutput is not the same though. Everything else is just weirdly working fine. Too quite to be true.

**Comment by Aga-C** [comment]
Thanks, it looks ok.
