### ISSUE TITLE
Enlargement of window with translated text

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#32]
I suggest adding the possibility of enlarging the window with the translated text.
This will make it easier to read long text. You won't need to scroll it in the translator window.

Open a separate window with the translated text by tapping the icon in the translated text window.
Of course, a separate window must also have a scroll bar and navigation to close the window or return to the translator 😉.

![obraz](https://user-images.githubusercontent.com/47037905/133738724-c8d11936-dfdc-4b2f-aa37-968ad9635ed9.png)

![obraz](https://user-images.githubusercontent.com/47037905/133739953-c47007e8-9f7c-4be7-9cad-b1826d14ed54.png)

**Comment by Valdnet** [comment]
I propose to add an enlargement and reduction of the text. This will help for users who have a slight visual impairment.

![obraz](https://user-images.githubusercontent.com/47037905/133773958-f5169433-f15d-4806-a59f-8b849fd12485.png)

**Comment by ManeraKai** [comment]
> I propose to add an enlargement and reduction of the text. This will help for users who have a slight visual impairment.

This setting is present on Android itself. It will enlarge apps by default.

**Comment by Valdnet** [comment]
> This setting is present on Android itself. It will enlarge apps by default.

Hmmm. Somehow I did not come across this in applications (except in the web browser).

**Comment by ManeraKai** [comment]
https://user-images.githubusercontent.com/40805353/133785143-a7faa5e3-c562-4446-bb4f-e3a928bdab43.mp4

**Comment by Valdnet** [comment]
We are talking about enlarging the font for the entire android system. Some users don't use it on a daily basis. They can do without it, but sometimes it's needed with more text. Then the eyes get tired. It is also too complicated for some users. Therefore, it requires the application to be handy and user-friendly. Adding this feature will make it easier for the user to achieve the goal.

**Comment by ManeraKai** [comment]
<img width=360 src="https://user-images.githubusercontent.com/40805353/133788012-54bf9d6b-d289-4fea-8838-9272b647f377.png">
<img width=360 src="https://user-images.githubusercontent.com/40805353/133788202-9e81cbee-827c-436b-96f8-b2dd9e01cc52.png">

**Comment by Valdnet** [comment]
I wasn't expecting a larger text for the window directly in the translator, but it turned out nice. You should add the same "+" and "-" in the big window.

![obraz](https://user-images.githubusercontent.com/47037905/133789205-3b7050df-1b5a-4267-9c1e-7f14caa5e626.png)

**Comment by Valdnet** [comment]
When the text is completely diminished, I get the following debugging error:

![obraz](https://user-images.githubusercontent.com/47037905/133994320-f0abbdb5-29da-4e1c-8c68-3902aa897b9d.png)

On the other hand, when the text is magnified very high, it goes beyond the window boundary:

![obraz](https://user-images.githubusercontent.com/47037905/133994451-839f931f-a4be-4b48-a7a3-ff64ff4fc7d8.png)

**Comment by Valdnet** [comment]
This issue is still:

![obraz](https://user-images.githubusercontent.com/47037905/133994451-839f931f-a4be-4b48-a7a3-ff64ff4fc7d8.png)

May provide a zoom limit for text. Why enlarge the text so much 😉.

**Comment by ManeraKai** [comment]
I really putted a limit, but you tried it on the maximized screen.

**Comment by Valdnet** [comment]
Yes. At the maximized screen 😉.

**Comment by ManeraKai** [comment]
This issue is fixed. Don't know which commit though.
