### ISSUE TITLE
Add themes

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#33]
Now is the time to add a light theme to this app 😁.
I propose to make an application in two themes (light and dark) that can be selected in the application settings.

Now it's standard in applications. Users require it.

**Comment by Aga-C** [comment]
I suggest 3 options of themes to choose: Follow system (it would be the default theme), Light and Dark.

**Comment by Valdnet** [comment]
> Follow system (it would be the default theme)

@Aga-C I thought about it as well, but I didn't want to tire the developer anymore 😁.

**Comment by ManeraKai** [comment]
Added Themes now. Light, Dark, Follow system. Didn't extract strings for translation yet. Design is still **under-development**.

**Comment by ManeraKai** [comment]
New strings for translation. Design may change though. So, maybe no need to translate now.

**Comment by Valdnet** [comment]
> So, maybe no need to translate now.

Take it easy @Aga-C  has already translated. These few text strings are "a piece of cake" for her 😉.

**Comment by Aga-C** [comment]
The light theme in the app should be improved.

![image](https://user-images.githubusercontent.com/85929121/133927376-32a95072-3bef-43f2-94f6-9e7eca219d82.png)

**Comment by ManeraKai** [comment]
I couldn't agree more

**Comment by Valdnet** [comment]
> The light theme in the app should be improved.

Exactly 😉. The background colors of the application (light gray) should be added.

**Comment by Valdnet** [comment]
Maybe something like this:

![obraz](https://user-images.githubusercontent.com/47037905/133933214-d67a75d8-0675-4f03-b60b-8f10d58a414c.png)

@Aga-C What do you think of such colors for a light theme?

**Comment by ManeraKai** [comment]
@Valdnet you version is old. There are tabs now.

**Comment by Valdnet** [comment]
I downloaded the last released: [Flutter build apk #18](https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1249360460).

**Comment by ManeraKai** [comment]
I'm sorry. Tabs were added two hours after that build. I've triggered it to run: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1251001171

**Comment by Aga-C** [comment]
@Valdnet I'd go rather with something like this (it's a quick sketch in UI design app, just for a preview):

![image](https://user-images.githubusercontent.com/85929121/133934401-04e161be-5de2-4b38-a536-5092f30a218d.png)

In my opinion, app bar should have the primary app color (one from the icon is the best), settings menu should be on the right, and tabs should have a different background than the rest of the app. Also, primary background should be white and there shouldn't be such dominant borders. It will make the app more consistent with Material Design guidelines.

**Comment by Valdnet** [comment]
@Aga-C Very nicely designed 🥇.

@ManeraKai We need something like that 😉.

**Comment by Valdnet** [comment]
You should also adjust the font color for the types of translators and match the colors of the "Tłimacz" button when the keyboard is active.

![obraz](https://user-images.githubusercontent.com/47037905/133935474-20846ceb-6bc4-4381-92b4-aff294b67b88.png)

**Comment by Valdnet** [comment]
The "Translate" text string is too low in the button.

**Comment by ManeraKai** [comment]
> The "Translate" text string is too low in the button.

You mean is the Aga-C's  sketch above or in compiled app app?

**Comment by Valdnet** [comment]
In a compiled application.

![obraz](https://user-images.githubusercontent.com/47037905/133939112-1c54fab2-ca8e-4710-9168-375e55e67c17.png)

**Comment by ManeraKai** [comment]
Fixed it.

**Comment by ManeraKai** [comment]
> settings menu could be on the right (so it would just show a popover instead of a sidebar), 

There'll be an about page. #23

**Comment by Aga-C** [comment]
> There'll be an about page. #23

I meant those two links that are currently in a sidebar menu. I think there is no need for a sidebar just for two pages, a simpler menu would be enough.

**Comment by ManeraKai** [comment]
I thought you meant a settings icon button TopRight. 
> a simpler menu would be enough.

Your right.

**Comment by ManeraKai** [comment]
I've added a file that includes everything for testing new designs, hopefully everything.
https://github.com/ManeraKai/simplytranslate-flutter-client/blob/main/assets/designs/main.svg

**Comment by ManeraKai** [comment]
My idea:
<img width=360 src="https://user-images.githubusercontent.com/40805353/133968709-e34b0d84-c2ea-4c43-8b04-7dc32aa0b3d2.png">

**Comment by Aga-C** [comment]
I wouldn't use such strong color for borders. It's too visible. In Material you'd rather use slight shadows. 
See here: https://material.io/design/color/the-color-system.html#color-theme-creation

**Comment by ManeraKai** [comment]
<img width=360 src="https://user-images.githubusercontent.com/40805353/133975616-ad44dcaf-f56b-4c05-8a52-99df3202aadc.png">
I didn't finish picking colors yet

**Comment by Aga-C** [comment]
Take a look into Material Design guidelines: <https://material.io/components/text-fields#usage>. It should be either a very slight border or a shadow, but the text field should have then a different background. Also, button (switch language) shouldn't look the same as text inputs. User should know it's a button. Also tabs

Also, it's a bit too colorful, in my opinion. Green, blue, pink - no need for so much contrasting colors. It would be even better to just use different shades of green and gray. Green from the icon should be a primary color, so a bit lighter/darker version of it should also be a color for active buttons. Translate button should also have this color. The button for language switch in my opinion should stay white as it's not a primary one. Also, I wouldn't use different color for language names. They should be standard black. With white and gray you can differentiate a bit background of text fields and app, or just use a slight gray for a thin border for them. 

By analogy, similar changes should be also done in the dark theme. In Material guidelines you will find everything about setting proper colors and how components should look: <https://material.io/>.

**Comment by Valdnet** [comment]
@Aga-C You wrote the directions very nicely 😉. You can see that you know it.

@ManeraKai I would also change the view in "Settings". I would not give windows to choose from, only a delicate menu with the possibility of clicking on a given setting function. Something like this:

![obraz](https://user-images.githubusercontent.com/47037905/133985575-27a28b03-0472-433e-8bd1-a0c07a537b86.png)

**Comment by ManeraKai** [comment]
<img width=360 src="https://user-images.githubusercontent.com/40805353/133986148-d923c500-e4ec-497a-95fc-b8c23b3ba65b.png">

**Comment by ManeraKai** [comment]
Do you have any suggestions, or I start implementing it?

**Comment by Valdnet** [comment]
It's great for me 👍.

**Comment by Aga-C** [comment]
And also for me 👍

**Comment by ManeraKai** [comment]
Great!

**Comment by ManeraKai** [comment]
> @Aga-C You wrote the directions very nicely wink. You can see that you know it.
> 
> @ManeraKai I would also change the view in "Settings". I would not give windows to choose from, only a delicate menu with the possibility of clicking on a given setting function. Something like this:
> 
> ![obraz](https://user-images.githubusercontent.com/47037905/133985575-27a28b03-0472-433e-8bd1-a0c07a537b86.png)

Can you show me a a picture of how it's pressed.

**Comment by Valdnet** [comment]
This is what it looks like:

![obraz](https://user-images.githubusercontent.com/47037905/134011604-e23f14fa-06c1-405a-b43c-fc841aca283f.png)

**Comment by ManeraKai** [comment]
A full screen menu?

**Comment by Valdnet** [comment]
Part of the menu:

![obraz](https://user-images.githubusercontent.com/47037905/134013468-83b3649d-3341-40a4-a8b8-ae019e46754a.png)

**Comment by ManeraKai** [comment]
Like this?
https://user-images.githubusercontent.com/40805353/134015052-2fa21c14-c19e-416d-ac1d-fbb436584442.mp4

**Comment by Valdnet** [comment]
In my opinion, unnecessary frames around the text string. When choosing a theme, add "radio".

**Comment by ManeraKai** [comment]
You mean the border on this right?:
![image](https://user-images.githubusercontent.com/40805353/134016214-e1ffa2c7-9c0f-4ce6-ade2-8abf39d770e9.png)

**Comment by ManeraKai** [comment]
> You mean the border on this right?:
> ![image](https://user-images.githubusercontent.com/40805353/134016214-e1ffa2c7-9c0f-4ce6-ade2-8abf39d770e9.png)

If you meant that. Don't worry, I was working on them. Just shared a snippet to ask about the full screen pop up menu.
Also:

https://user-images.githubusercontent.com/40805353/134024477-097f8f56-8f96-4e7e-9526-067ac6e7803f.mp4

**Comment by Valdnet** [comment]
@ManeraKai This is what it was about. Of course, the instance selection also needs to be changed 😉.

**Comment by ManeraKai** [comment]
Working on it:
![image](https://user-images.githubusercontent.com/40805353/134035449-eecbbeef-7c93-41f7-a0c9-96c979a0fdf0.png)

**Comment by Valdnet** [comment]
Cool 😉 . I'm starting to like it 👍.

**Comment by ManeraKai** [comment]
What do you think @Valdnet?

https://user-images.githubusercontent.com/40805353/134164957-73b7bae9-3083-4a04-9da7-f4bd059ed1ff.mp4

**Comment by Valdnet** [comment]
@ManeraKai Cool 👍. It looks very good now. Good job.

**Comment by ManeraKai** [comment]
This issue is about to be closed. Anything else @Valdnet and @Aga-C?

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1257599260

**Comment by Valdnet** [comment]
Should be improved as to the functionality of the settings:
1. Right after installing the application and starting it, the theme is set to "System". On entering the theme settings it is marked as "Dark". Should be set to "Follow system".

![obraz](https://user-images.githubusercontent.com/47037905/134175232-6defc701-ce8e-4c8f-92a7-1310af62df15.png)

![obraz](https://user-images.githubusercontent.com/47037905/134175365-e2498835-bdd8-4b91-bab2-084bf418e08c.png)

2. All text strings with the description of the set function should start with a capital letter, except for the instance addresses.

![obraz](https://user-images.githubusercontent.com/47037905/134176580-e54ace8b-03a7-4fff-97d0-b793e61e5e99.png)

3. After selecting an option, the window should close by itself.

**Comment by ManeraKai** [comment]
> Right after installing the application and starting it, the theme is set to "System". On entering the theme settings it is marked as "Dark". Should be set to "Follow system".

Fixed

>All text strings with the description of the set function should start with a capital letter, except for the instance addresses.

Fixed

>After selecting an option, the window should close by itself.

Added

> @Aga-C Does the light blue color of the window borders and text match the theme? It doesn't suit me very well.

Turned out that I wrote `0xffa9a9a9ff` instead of `0xffa9a9a9`

> There are unnecessary margins on top of settings and inside of themes popup

Fixed

> Theme popup should have a cancel button in the bottom-right corner

 Added

> I wouldn't use green for borders of language inputs, also gray.

It will look like they're disabled. The copy, paste, etc.. icons have the green color as enabled, grey as disabled.
Do you mean changing the border color only and not the text?

> I think you could use different icon for Theme setting. A moon fits only dark theme, so it would be better if the icon would be more universal, or you can change icon to sun when there is a light theme. However, it wouldn't fit "system" setting. How about `brightness_medium` icon from Material?

If the theme was on system, it'll pick system's theme icon. it will be practical as the app itself is themed already.

> Radio buttons circle shouldn't be blue but have a primary color (green)

Changed

> Also, I think you can use the green primary color for dark theme too, to make the app more consistent. However, you can use a slightly darker green.

This will move the app's dark theme design away from melatune's design. If both of you wanted it to be Material Design and not metalune's design, I'll do that and round the corners @Valdnet 😁

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1258590374

**Comment by ManeraKai** [comment]
<img width=360 src="https://user-images.githubusercontent.com/40805353/134219596-fda47e74-c3a9-48fa-a400-9b0ce540f6f6.png">

**Comment by Valdnet** [comment]
Something beautiful for you comes out 👍.

**Comment by ManeraKai** [comment]
<img width=360 src="https://user-images.githubusercontent.com/40805353/134227063-a053a7e3-95e4-4a5e-a4ce-daa1f501cb0d.png">
What do you think?

**Comment by Valdnet** [comment]
Too dark green in my opinion. What do you think @Aga-C?

**Comment by Aga-C** [comment]
I think this green looks ok, but I'd do green top bar too.

**Comment by ManeraKai** [comment]
Btw: I forgot that primary colros shouldn't be saturated in dark mode. The green color should be de saturated.

> I think this green looks ok, but I'd do green top bar too.

This isn't allowed in the Material Design guidelines.

**Comment by Aga-C** [comment]
> This isn't allowed in the Material Design guidelines.

Yes, but it's still allowed if you'd use darker color. For example, you can see how it's described here: <https://blog.prototypr.io/how-to-design-a-dark-theme-for-your-android-app-3daeb264637> (branded dark surface and dark primary). Currently, it looks nice, but you can try something like this. App can look even better.

**Comment by Valdnet** [comment]
What do we do with the dark theme? I propose to add a green bar under the translator selection according to the screenshot below:

![obraz](https://user-images.githubusercontent.com/47037905/134296849-976581f2-2ea1-4c75-b97e-32e83fc5b152.png)

**Comment by Valdnet** [comment]
For a lightweight theme, please correct the font color of the message below.

![obraz](https://user-images.githubusercontent.com/47037905/134383177-bb50ad09-4805-4674-a585-f23d346c7d18.png)

@ManeraKai And be sure to add green for the dark theme described in the comment above 😉.

**Comment by Valdnet** [comment]
And here's the same thing:

![obraz](https://user-images.githubusercontent.com/47037905/134387257-b4668cad-a16c-4796-b95f-c22a2353c594.png)

**Comment by Valdnet** [comment]
I would reduce the font size of the messages.

**Comment by Valdnet** [comment]
I think this issue can be closed. Possible corrections will be discussed in issue #87.
