### ISSUE TITLE
Move "Check" button and add a border

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#34]
I propose to move the "Check" button to the right side and add a border with rounded corners.

![obraz](https://user-images.githubusercontent.com/47037905/133772295-d1b5bbc7-97af-4d48-a14a-d2e4d07b7858.png)

**Comment by ManeraKai** [comment]
What about the translate button. Either both of them on right or left.
?

<img width=360 src="https://user-images.githubusercontent.com/40805353/133859842-bd809d92-c32b-4a76-a49d-c6b2cc19ab9c.png"> <img width=360 src="https://user-images.githubusercontent.com/40805353/133859845-98d5f2d6-7f45-4630-a62c-b2309d0b1080.png">

<img width=360 src="https://user-images.githubusercontent.com/40805353/133860705-5a6bff5c-de1e-46ce-a150-8ba555396e1f.png"> <img width=360 src="https://user-images.githubusercontent.com/40805353/133860709-4c8bd850-ebfd-48fe-89df-0aa4456ea7dc.png">

**Comment by Valdnet** [comment]
Both on the right :wink:.
