### ISSUE TITLE
Switching translation languages

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#38]
Steps:

1. Paste the text for translation.
2. Switch translation languages with "<>".

The translated text automatically appears in the second window, while the top window is blank.

Screenshot:

![obraz](https://user-images.githubusercontent.com/47037905/133836108-e6ee53f3-b323-4afb-9f99-9a36fff763ba.png)

App:
Simply Translate 1.0.0

**Comment by ManeraKai** [comment]
No need for the pasting step. Just type and don't submit (Enter) .The Translate button won't be triggered. Therefore no text is translated. Switching will take the original text and swap it with the not translated yet text which will be blank.
Do you want to trigger translation when pressing the Switch button?

**Comment by Valdnet** [comment]
> Do you want to trigger translation when pressing the Switch button?

Yes. Each language switch should be translated. So first it translates and then changes the text. This is what Google Translator does. The second reason that the first blank window looks strange is when the second window contains text.

**Comment by Valdnet** [comment]
Scheme of translation, so as not to "get lost" 😁.

A - upper window with the text to be translated
B - bottom window with translated text
<-> - language change button
aaa - text to be translated
bbb - translated text
ccc - next translation
ddd, eee - next translation of the translation


1. The first with only the text entered in window A and pressing the button `<->`:
A - aaa
B - empty
`<->`
A - empty
B - empty

2. Text translation by the `Translate` button and subsequent language change with the `<->` button:
A - aaa
B - empty
`Translate`
A - aaa
B - bbb
`<->`
A - bbb
B - ccc

3. Next language changes with the `<->` button:
A - bbb
B - ccc
`<->`
A - ccc
B - ddd

4. Deleting the text from window A with the ` X` button and then changing the language with the `<->` button:
A - empty ` X`
B - ddd
`<->`
A - ddd
B - eee

**Comment by ManeraKai** [comment]
> When translating the text, e.g. from PL -> EN and back to PL (to be checked and corrected), you can choose the best words in the sentence to make it understandable in the translated text.

How?

**Comment by Valdnet** [comment]
> How?

This is "magic" :grin:. Note that this is just, or up, a program that translates according to your scripts. One word in a sentence can be translated differently. And with the method that I described earlier, you can choose the words so that the end result of the sentence makes sense.
