### ISSUE TITLE
"Enter" as line break

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#39]
When writing the text to be translated, the "Enter" key should start a new line of writing. Currently, it starts translating immediately.

**Comment by ManeraKai** [comment]
Thought of this. Either you have the `Enter` key or `Auto Translating`. You can't live without one of them.

**Comment by Valdnet** [comment]
I don't know if we understood each other well.

"Enter" - new line
"Translate" - translation

**Comment by ManeraKai** [comment]
> Enter means submitting the form so translating

A quote from my brain dictionary

I think you meant to change Enters key functionality from submitting to adding a new line?

**Comment by Valdnet** [comment]
> I think you meant to change Enters key functionality from submitting to adding a new line?

Yes :+1:.

**Comment by ManeraKai** [comment]
@Valdnet It'll be done like that: https://github.com/ManeraKai/simplytranslate-flutter-client/pull/40#issuecomment-922257911

**Comment by ManeraKai** [comment]
Changed it. Added a float button for translation:
<img width=360 src="https://user-images.githubusercontent.com/40805353/133923846-c918e0fd-7774-435c-8cf2-ee46d6d46d4b.png">

**Comment by ManeraKai** [comment]
Any design issue will be discussed here #33

**Comment by Valdnet** [comment]
The "Enter" key on the keyboard does not work. After tapping a key, it does not start a new line.

**Comment by ManeraKai** [comment]
working fine on my emulator. Downloaded last artifact to my real device. Working fine too.

**Comment by Valdnet** [comment]
On my Android 10 smartphone, something like this is happening:

![obraz](https://user-images.githubusercontent.com/47037905/134812932-115396cf-3dde-4c4e-a3b5-db4ca7548001.png)

**Comment by ManeraKai** [comment]
Try to restart the device. I know one thing that may be causing this problem.

**Comment by Valdnet** [comment]
> Try to restart the device.

Did not help. There is something in the application 😉.

**Comment by ManeraKai** [comment]
Hope it works: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1275434226

**Comment by Valdnet** [comment]
No change. The "Enter" key still does not work.

**Comment by ManeraKai** [comment]
Can you try it on another device, because I really didn't change anything.

**Comment by Valdnet** [comment]
Previously, it worked on my smartphone 😁.

**Comment by ManeraKai** [comment]
One minute. Do the previous artifacts work fine at the moment?

**Comment by Valdnet** [comment]
The artefact #50 does not work properly.

**Comment by Valdnet** [comment]
Maybe this commit did something wrong: https://github.com/ManeraKai/simplytranslate-flutter-client/commit/419982cfeb5f4fd230d7245a2c2a07ebf5332247

**Comment by ManeraKai** [comment]
This commit was about the `TextSelectionToolbar`

**Comment by Valdnet** [comment]
Other commits would probably not break it.

**Comment by ManeraKai** [comment]
Let me try to comment the customization of the `TextSelectionToolbar` and see what happens.

**Comment by ManeraKai** [comment]
`TextSelectionToolbar` is disabled: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1275539214

**Comment by Valdnet** [comment]
There is still a problem 😬.

**Comment by Valdnet** [comment]
For black theme, a gray frame appears around the window when I tap the "Enter" key. Maybe it will help?

![obraz](https://user-images.githubusercontent.com/47037905/134816691-41665744-8772-48b4-9fa0-5cb1e05b2973.png)

**Comment by Valdnet** [comment]
This frame can be the glow of that gray background that appears in a light theme.

**Comment by ManeraKai** [comment]
Try to paste multi line text

**Comment by Valdnet** [comment]
> Try to paste multi line text

I can paste without any problem.

**Comment by ManeraKai** [comment]
So you can paste. Can you add a new line or what can you and can't you do now?

**Comment by Valdnet** [comment]
If I paste a new line, I can only delete it.

**Comment by ManeraKai** [comment]
Can you try to change from Swift keyboard to the stock one.

**Comment by ManeraKai** [comment]
btw I meant pasting from the toolbar options. Not from the side buttons.

**Comment by Valdnet** [comment]
I can paste new lines from the toolbar and just delete them.

I noticed that when I type a space character tapping the "Enter" key removes it. If he enters several space characters, he removes them one by one each time he taps the "Enter" key, until it encounters a character, e.g. letters or numbers.

**Comment by Valdnet** [comment]
When removing the space characters with the "Enter" key, there is still a glow in the window, which I showed above in the screenshot.

**Comment by Valdnet** [comment]
> Can you try to change from Swift keyboard to the stock one.

I don't have another keyboard in my system.

**Comment by Valdnet** [comment]
When selecting a language from the list of languages, the "Enter" key works correctly. Selects the given language.

**Comment by ManeraKai** [comment]
I'll disconnect the controller for that TextField. So You'll have just a vanilla multi-line TextField to type in, without character limit or anything like that.

**Comment by ManeraKai** [comment]
Or one minute, my emulator doesn't detect my keyboard Enter key. When I disabled the custom `TextSelectionToolbar`, I forgot that the textfield was wraped by  a `TextSelectionToolbarTextButton` widget: 
![image](https://user-images.githubusercontent.com/40805353/134821951-fbf8d705-2458-40df-b70e-76ad73625009.png)
Going to delete that and see, but this will disable the custom `TextSelectionToolbar`.

**Comment by ManeraKai** [comment]
The glow even appeared for me too.

**Comment by ManeraKai** [comment]
I'm confident it will work: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1275877228

**Comment by Valdnet** [comment]
It works in this version 👍.

**Comment by ManeraKai** [comment]
Means that it's because of the custom `TextSelectionToolbar`

**Comment by Valdnet** [comment]
You mean we can't use it?

And there will still be a problem with issue #61.

**Comment by ManeraKai** [comment]
Issue #61 is not a critical one as this issue. I'll find a fix for it, but we should get a release running at the time, because there has been so many changes done. Some Instances have even changed their domain name. We don't have time.

**Comment by Valdnet** [comment]
Well. Release a new version 😉.

Check also PR #109.

**Comment by ManeraKai** [comment]
> Check also PR #109.

I've added some comments.
