### ISSUE TITLE
add the option to select the translation engine

### ISSUE THREAD

**Issue by darhma** [ManeraKai/simplytranslate-flutter-client#4]
From the website https://translate.metalune.xyz/ you can select the translation engine (google/libretranslate) it would be useful to add a similar option in the app as well.

**Comment by ManeraKai** [comment]
I'm adding query parameters to the url for selecting the engine. But it gives me an error:
![image](https://user-images.githubusercontent.com/40805353/133217098-5705c99a-c16c-487e-b7e8-c82486115582.png)

I tried to use [twitter](https://twitter.com/)'s server and added the `lang` parameter to see if the UI language will change and it worked just fine:
Arabic:
![image](https://user-images.githubusercontent.com/40805353/133218191-eaa24768-150a-4bf0-bb0d-a3aea18b560f.png)
Spanish:
![image](https://user-images.githubusercontent.com/40805353/133218407-a05973ad-d32c-472c-82fc-aeac58814827.png)

Note that if I changed the parameter to anything other than `libre`, it won't give an error and will translate the text:
![image](https://user-images.githubusercontent.com/40805353/133218834-9719e317-524a-4826-a3dc-64d723714bec.png)
Maybe it's a server side problem.

**Comment by ManeraKai** [comment]
**Update:** it's now weirdly working just fine. Too quiet to be believed. Don't know what happened:
![image](https://user-images.githubusercontent.com/40805353/133587720-4ab50f4c-8b06-4802-b2d3-016e6447fc6a.png)

**Comment by darhma** [comment]
I tried to enter https://metalune.xyz/?engine=libre as a custom server but it didn't work.

**Comment by ManeraKai** [comment]
You forgot the subdomain `translate`: `https://translate.metalune.xyz/?engine=libre`

**Comment by darhma** [comment]
I just tried again with https://translate.metalune.xyz/?engine=libre but it still doesn't work.

**Comment by ManeraKai** [comment]
I think it's because I didn't add support for parameters. If you inject it in the code though. It will work.
I'm now working on it.

**Comment by ManeraKai** [comment]
**Note:** If the instance didn't have LibreTranslate turned on. The client won't detect that yet.

**Comment by ManeraKai** [comment]
I've now added LibreTranslate detection.

**Comment by darhma** [comment]
I am trying the app again but I don't understand how to select LibreTranslate as the translation engine, even using an instance that supports it like https://simplytranslate.org/ it is still possible to select a different engine or it is a feature that has been deleted?

**Comment by ManeraKai** [comment]
The support for an engine other than GoogleTranslate has been removed. We'll readded though. There were so many bugs and conflictions that we needed to remove it.
