### ISSUE TITLE
Text string in Latin

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#43]
@ManeraKai Why is it in Latin :hushed:?

https://github.com/ManeraKai/simplytranslate-flutter-client/blob/a5f08092f016b8e9c0b1daafec24b329c9f81074/lang/main_en.arb#L134

**Comment by Aga-C** [comment]
`In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.`

<https://en.wikipedia.org/wiki/Lorem_ipsum>

**Comment by ManeraKai** [comment]
The page is still under development.

**Comment by Valdnet** [comment]
And that surprised me. I have not encountered this 😁.
