### ISSUE TITLE
Incorrect operation glow

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#44]
Window glow does not work properly for a window that is full with text.

Before entering the text:

![obraz](https://user-images.githubusercontent.com/47037905/133930273-dd90995a-0fe2-4e7b-a9a2-504da03f4987.png)

After you populate the window with text:

![obraz](https://user-images.githubusercontent.com/47037905/133930262-fdda02cb-3d15-4754-a7aa-f59012e483c0.png)

**Comment by ManeraKai** [comment]
Just don't put your finger on the text. Put it on the right side:
<img width=360 src="https://user-images.githubusercontent.com/40805353/133930445-a639ffa2-f660-4835-81fa-9f65816c6f00.png">

**Comment by Valdnet** [comment]
Ok. Yes it can be 😉.
