### ISSUE TITLE
Application crashes after restarting

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#47]
Steps:

1. Launch the application.
2. Minimize the application to run in the background via the **smartphone's navigation arrow**.
3. Restart the application, e.g. from an icon on the desktop.

The application is shutting down.

**Comment by ManeraKai** [comment]
Didn't crash on mine.

**Comment by Valdnet** [comment]
> Didn't crash on mine.

It will now be a problem detecting an issue 😬.

My system is Android 10 and a Huawei device.

**Comment by ManeraKai** [comment]
Does it crash every time?

**Comment by Valdnet** [comment]
> Does it crash every time?

It is every time. I run the application, exit via the arrow selecting from the system navigation and restart the application, either from the desktop icon or from processes. The application turns off every time.

**Comment by ManeraKai** [comment]
Last artifact that was builds minutes ago, yes?

**Comment by Valdnet** [comment]
The old one from that day. I download a new one immediately and test it.

**Comment by Valdnet** [comment]
@ManeraKai The same is also true of the new version.

**Comment by ManeraKai** [comment]
Tried it on my phone. If I press the home button. Nothing will happen. Back button will crash it. Sorry, I thought you said any navigation button.
