### ISSUE TITLE
Translation from the "Kebab" menu

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#48]
Steps:

1. Select the text to copy.
2. Select the "Simply Translate" program from the "Kebab" menu.
3. Press the "Translate" button in the application.

The text was translated in Arabic even though the language is set to Polish.

Unless it's a developer diversion (joke) 😁.

![obraz](https://user-images.githubusercontent.com/47037905/133932081-0bde3ba3-5e30-49d9-a1c0-b26a641ac796.png)

**Comment by Valdnet** [comment]
Additionally, the translation should be automatic, without selecting the "Translate" button.

**Comment by ManeraKai** [comment]
If you try to launch the app. Right and translate without touching the from and to lang buttons. The same effect will happen.

**Comment by Valdnet** [comment]
> Additionally, the translation should be automatic, without selecting the "Translate" button.

This is not in the app.

**Comment by ManeraKai** [comment]
I ran an `.apk` build action if you wanted: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1253247314
