### ISSUE TITLE
Heavy performance of application processes

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#50]
I noticed that after the changes made, the application is working slowly:

- It starts very slowly
- When selecting a menu for the first time, eg "Settings", it also loads slowly
- When selecting settings in the "Settings" section, etc.

This happens after the first election. Later it works fairly well, but still too slow. Is it possible to speed up the loading of the application and its functions?

**Comment by ManeraKai** [comment]
The artifacts that you download are debug versions. Android doesn't allow unsigned release builds to be installed. You should plug your phone to your computer and run flutter release I think.

**Comment by Valdnet** [comment]
Well. So in the official version released, everything will run much faster. So I'm closing the issue 😉.
