### ISSUE TITLE
Scroll to side

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#51]
I suggest that the choice of translator can be switched by sliding a finger. Right now, it's just a tap on him.

![obraz](https://user-images.githubusercontent.com/47037905/133934805-3664251c-71e9-4b0a-8ba3-7d6ab7d397fe.png)

**Comment by ManeraKai** [comment]
I've disabled this on purpose as it'll disturb typing. Changing engine is so rare that it's not a priority over typing comfortably.

**Comment by Valdnet** [comment]
Ok. So I'm closing the issue.
