### ISSUE TITLE
Gray icons with no translated text

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#53]
For consistency for icons, in the translation window, when there is no text, change the following icons to inactive:

![obraz](https://user-images.githubusercontent.com/47037905/133935057-de4ec827-a93f-439a-bc8a-530e396d2eaf.png)

**Comment by Aga-C** [comment]
And in my opinion, `+` and `-` icons should be closer to each other.

**Comment by ManeraKai** [comment]
It's the icons shape fault. It was the `minimize` icon. Now I've found the real minus icon under the name `remove`.
