### ISSUE TITLE
Add a character limit to translate input

### ISSUE THREAD

**Issue by Aga-C** [ManeraKai/simplytranslate-flutter-client#54]
GoogleTranslate and LibreTranslate have 5000 characters limit. Because of that, the translation input should have a character limit to prevent errors. When pasting text, it should be cut off after reaching characters limit.

Also, it would be useful for users to see a character counter, like it is in GoogleTranslate, to see how much they can still write.
![image](https://user-images.githubusercontent.com/85929121/133936789-4d93d1f9-3922-4ab5-a820-13ead2762be1.png)

**Comment by Valdnet** [comment]
After sending such a long text for translation, we only get an empty window with the translation.

Solution:
Displaying a message with information about exceeding the number of characters.

**Comment by ManeraKai** [comment]
I've fixed the bug as the user can't even press the translate button now. Does it look good design wise though?

**Comment by Aga-C** [comment]
@ManeraKai Yes, it looks great 👍
As for the action, remember to refresh the counter while pasting by the icon (and by sharing from another app too). When this function will be complete, I would say more about it.
And the most important thing - maybe it's time to fix every issue, add About content and release a new version? For now, there are many improvements.

**Comment by Valdnet** [comment]
> And the most important thing - maybe it's time to fix every issue, add About content and release a new version? For now, there are many improvements.

But only after my complete testing 😜.

**Comment by Aga-C** [comment]
@Valdnet 👍

**Comment by Valdnet** [comment]
I propose to lower the information about the number of characters down. It misleads the user that it is a functional icon.

![obraz](https://user-images.githubusercontent.com/47037905/134306092-3de3582c-dc4a-4495-aaf2-07942ca7e916.png)

**Comment by Aga-C** [comment]
In case of change, I'd leave it inside the text field similarly as it is in Google Translate.

**Comment by Valdnet** [comment]
@Aga-C Of course 😉. The information is well placed in the window, just lower it slightly to separate it from the rest of the edit icons. According to the screenshot above.

**Comment by ManeraKai** [comment]
> I propose to lower the information about the number of characters down. It misleads the user that it is a functional icon.

Lowered that.

**Comment by ManeraKai** [comment]
Any suggestion as those bugs are fixed now?

**Comment by Valdnet** [comment]
If you corrected it, you can close the issue. If I find something in the tests, I will ask you to open it again.

BTW: Can you set a case to be opened to the author? Currently, I am not permission to do so.

**Comment by ManeraKai** [comment]
@Valdnet, sent a collaborator invitation.

**Comment by Valdnet** [comment]
> sent a collaborator invitation.

Thanks. I confirmed them 😉.
