### ISSUE TITLE
"Paste" icon after translation

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#57]
Steps:

1. Enter the text to translate.
2. Tap the "Translate" button.
3. Tap the "Paste" icon.

Unable to paste text into existing text in the window to be translated (this causes the "pipe" to be missing).

I suggest:
Either the "Paste" icon should be gray to let the user know that pasting is inactive, or the text should be pasted at the end of the sentence.

![obraz](https://user-images.githubusercontent.com/47037905/134001302-09fb3add-2f94-4293-a444-694255315e6c.png)

**Comment by ManeraKai** [comment]
You mean at the moment of requesting and loading from the server, you pressed on the paste button?

**Comment by Valdnet** [comment]
Not. After translation, when the `|` sign disappears from the text the "Paste" icon is still active. This proves that the user can still paste the text into the translation. If the button "Paste" is blunted, no action is taken (it does not attach the text to the end of the sentence).

Ideally, the icon should be gray until the user again selects where to paste the text.

**Comment by ManeraKai** [comment]
Is the cursor the pipe sign?

**Comment by Valdnet** [comment]
> Is the cursor the pipe sign?

Yes. Professionally, this is what it is called 😉.

After translating the text:

![obraz](https://user-images.githubusercontent.com/47037905/134003651-0dfd13a3-de8d-4117-a347-187fea553a47.png)

After selecting where to paste the text in the window:

![obraz](https://user-images.githubusercontent.com/47037905/134004052-9aacec4b-e247-4441-bcd1-727b4b9adc2a.png)

**Comment by Valdnet** [comment]
But you have to take into account that if the window is empty, you can paste the text directly via the "Paste" icon 😉.

**Comment by ManeraKai** [comment]
Fixed it. There was a bug in the code. It was looking for cursors position but didn't found it. That's why it didn't paste. Now it will paste every time.
