### ISSUE TITLE
Clearing translation window in second translator

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#59]
Steps:

1. Enter the text to be translated.
2. Tap the "Translate" button.
3. Go to the second translator.
4. Tap the "Translate" button.
5. **Edit the text** to be translated.
6. Tap the "Translate" button.
7. Go to the previous translator.

The translation window should be cleared. Currently misleading the user about the translated text.

![obraz](https://user-images.githubusercontent.com/47037905/134011308-25d5c7ed-f3b4-466f-b8dd-b1be6dd920dc.png)

**Comment by ManeraKai** [comment]
>The translation window should be cleared. Currently misleading the user about the translated text.

Should be cleared? You didn't press the delete button.
Did you mean that if you pressed the delete button on one of them. It won't trigger the other's translated text to be removed?

**Comment by Valdnet** [comment]
@ManeraKai Issue needs to be reopened and think about a sensible solution.

> That's what I meant. Pressing "X" (Delete) should clear the windows for the second translator as well. This will remove any doubts about the translation described in this issue.

This description is for issue #58.

**Comment by ManeraKai** [comment]
If it's like that.
>The translation window should be cleared.

Then how this one should be cleared without pressing the delete button?

I'm now talking about this issue.

**Comment by Valdnet** [comment]
> Then how this one should be cleared without pressing the delete button?

In the second translator, the text in the translated text window should be deleted when some text change has been made in the window for translation after pressing the "Translate" button or changing the <-> languages.

Scheme:

GoogleTranslate
**A** - window for the text to be translated
**B** - window for translated text

LibreTranslate
**A** - window for the text to be translated
**C** - window for translated text

1. I insert my text into window **A**.
2. Translators via the "Translate" button.
3. I switch to the second translator.
4. Translators via the "Translate" button.
5. I am **changing** the text in window **A**.
6. Translators via the "Translate" button.

- This is where the text in window **B** should be deleted, the application must check if there is a change in the text for window A. If so, it deletes the text in window **B**.
- Same operation when changing languages via button **<->**.

Same rule for both translators, no matter which one you use.

This will eliminate user confusion. In the current version, the user, after translating the text in both translators, and then after changing the text in one translator and going to the other, has the old translation for the new text. He doesn't see the difference. He does not know if the translation of the new text has also happened here. If you see a blank window for the translated text you know you have to translate it again.

**Comment by Valdnet** [comment]
Please open an issue and reconsider my solution 😉.

**Comment by ManeraKai** [comment]
I thought it was a bug. But your last comment was so clear. Fixed it now.

**Comment by Valdnet** [comment]
> Fixed it now.

Cool 👍.
There are still issues pending reopening:

Issue #19
Issue #61

**Comment by Valdnet** [comment]
> This is where the text in window B should be deleted, the application must check if there is a change in the text for window A. If so, it deletes the text in window B.

This condition is not implemented.

**The application must check if there is a change in the text for window A.**

**Only** deletes window **B** or **C** when there is a **change** in window **A**.

The user must be able to check and compare the translation from window **B** with window **C**.

**Comment by ManeraKai** [comment]
This issue is not as easy as what I thought. From now on. LibreTranslate widgets will not longer be the same as GoogleTranslate ones. Currently, they are the same widget but with changing some elements. This confuses Flutter so much that it doesn't edit the right engine input or output. Further more, TTS is on the door. The interfaces will be different.

**Comment by Valdnet** [comment]
So it turns out that we have to give up LibreTranslate?

**Comment by ManeraKai** [comment]
They'll just be seperated, mainting both of them requires work. It's even disabled by default on simplytranslate servers. It requires subscribtion to run if you didn't host it on your server.
It's not that we won't use it forever. Just maybe not for this release.
What do you think?

**Comment by ManeraKai** [comment]
Adding TTS features will even separate http request functions.

**Comment by Valdnet** [comment]
> It's not that we won't use it forever. Just maybe not for this release.
> What do you think?

You mean you only want to use GoogleTranslate in this release? I'm for 😉.

**Comment by Valdnet** [comment]
So I close the issue.
