### ISSUE TITLE
Text over 5000 characters

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#63]
Steps:

1. Enter over 5,000 characters.
2. Tap the "Translate" button.

After sending the text for translation, we only get a blank window.

There should be information about exceeding 5000 characters.

Issue to: #54.

**Comment by ManeraKai** [comment]
Fixed: https://github.com/ManeraKai/simplytranslate-flutter-client/commit/22fa841cda25063f062c1853013ef6b74167f792
