### ISSUE TITLE
Keyboard rotation

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#64]
Steps:

1. Launch the application.
2. Tap on the window to enter text.
3. Rotate the smartphone horizontally.

![obraz](https://user-images.githubusercontent.com/47037905/134044609-b17f95be-f41c-4d0d-ba81-2285504ffd57.png)

The keyboard covers the text editing window, which is normal, but you can get around this by adding an additional text input preview window. For example something like this:

![obraz](https://user-images.githubusercontent.com/47037905/134044801-cf357f87-6484-4fef-afaa-fb0379ae3ec4.png)

**Comment by ManeraKai** [comment]
Disabled Status bar upon rotating landscape, AppBar upon opening the keyboard:
![Screenshot_1632229601](https://user-images.githubusercontent.com/40805353/134175891-8817a744-dbf7-4d58-b51a-cf1d481b0824.png)
