### ISSUE TITLE
Add New Instances and Remove non-working ones

### ISSUE THREAD

**Issue by metalune1** [ManeraKai/simplytranslate-flutter-client#65]
As of today, https://translate.metalune.xyz should no longer be used, please use https://simplytranslate.org instead, also, there is another instance https://st.alefvanoon.xyz (you can see a listing here: https://simple-web.org/projects/simplytranslate.html) although instead of adding these instances manually, I'd rather recommend just fetching a list in plaintext using this endpoint: https://simple-web.org/instances/simplytranslate

**Comment by ManeraKai** [comment]
> please use https://simplytranslate.org instead

👍
> there is another instance https://st.alefvanoon.xyz

Noticed that but didn't added it. I'll added though.

> I'd rather recommend just fetching a list in plaintext using this endpoint

👍

**Comment by ManeraKai** [comment]
This feature has been added. There is a button now to update from the official instances list:
<img width=360 src="https://user-images.githubusercontent.com/40805353/134468373-47c3c821-93c9-4c34-b0b3-ce65f5378555.png">
Design wise things will be discussed on another issues.

**Comment by metalune1** [comment]
Awesome!
