### ISSUE TITLE
Editing window for language setting

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#70]
Steps:

1. Select the text in the language settings window.
2. Paste the copied text or enter your own.

You get something like the screenshot. Possibility to select a language only from the list.

![obraz](https://user-images.githubusercontent.com/47037905/134220382-5dab10f4-6361-4a6d-9568-cdb79157dbd5.png)

![obraz](https://user-images.githubusercontent.com/47037905/134220293-33a2029f-7119-41c7-bfad-d246b74ad9e8.png)

**Comment by ManeraKai** [comment]
How does it translate?

**Comment by Valdnet** [comment]
It translates well. It selects the last language set, but something like this should not be present, so that you can paste or type whatever you want. This does not reflect well on the application. There should **only** be a language selection from the list.

**Comment by Valdnet** [comment]
Of course, changes for both language selection windows 😉.

**Comment by ManeraKai** [comment]
Fixed it. Though it won't revert back to the previous selected language if the user just pressed back and didn't press the submit (enter) button.
It will revert back only if the user submited (pressed enter key) the value.
