### ISSUE TITLE
Remove "Translate" button when setting language

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#71]
For language selection, the "Translate" button should be hidden. The user will know that they need to select a language before translating.

For language selection, the "Translate" button above the keyboard should be hidden. After a more detailed search, the "Translate" button suddenly appears, which is covered with the language selection window. It looks a bit strange. Additionally, the user will know that they need to select a language before translating.

![obraz](https://user-images.githubusercontent.com/47037905/134221821-119b3cb4-4347-4edd-a63a-c9ec43098192.png)

![obraz](https://user-images.githubusercontent.com/47037905/134221348-1c26d7f2-b21c-4064-8e57-5847d8ef1cbe.png)

**Comment by ManeraKai** [comment]
>the user will know that they need to select a language before translating

He really doesn't need as nothing will break if he didn't select a language. Will just fallback to the previous selected one.

It won't break it the app, but do you want it to be hidden for UX reasons?

**Comment by ManeraKai** [comment]
Fixed. The floating translate button will appear just when writing in the translation input.

**Comment by Valdnet** [comment]
A test version, please 😉.

And please open this issue #59. It is still very important.

**Comment by ManeraKai** [comment]
>A test version, please wink.

https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1260668750

>And please open this issue

Don't you have the permission to reopen as you are the creator of it?

**Comment by Valdnet** [comment]
> Don't you have the permission to reopen as you are the creator of it?

I have no permission 😬.
