### ISSUE TITLE
Add a notice that this is an Unofficial Client

### ISSUE THREAD

**Issue by metalune1** [ManeraKai/simplytranslate-flutter-client#72]
I'd like for you to add a note to the README.md and the F-Droid Description stating that this is an unofficial client for SimplyTranslate and not a part of the Simple Web project, just for formalities and to avoid confusion :)

**Comment by metalune1** [comment]
Awesome, also, just fyi and in hopes that you don't have anything against it, we now put a link to this github page on https://simple-web.org/projects/simplytranslate.html

**Comment by ManeraKai** [comment]
Of course no problem.

**Comment by ManeraKai** [comment]
The title has changed to: `Simply Translate (Unoffical)`
short discription: `An unofficial app client that connects to multiple Simply Translate instances.`
long discription: `<p>Metalune created a <a href="https://translate.metalune.xyz/">web client</a> for SimplyTranslate, and I created an unofficial mobile client.`

**Comment by metalune1** [comment]
correction: `<p>Metalune created a <a href="https://simplytranslate.org">web frontend</a> for SimplyTranslate, and I created an unofficial mobile client.` would make more sense imo

**Comment by metalune1** [comment]
this link is also no longer active, as simple-web.metalune.xyz became simple-web.org

**Comment by ManeraKai** [comment]
Changed them.

**Comment by ManeraKai** [comment]
@Aga-C  They need some minor translation.
