### ISSUE TITLE
Icon inactive "Paste" when clipboard is empty

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#74]
The "Paste" icon should be inactive when the clipboard is empty. Currently, the user taps the "Paste" icon and there is no reaction. He doesn't know why this is happening. The application should check if there is any text in the clipboard, if so, the "Paste" icon should be activated.

**Comment by ManeraKai** [comment]
This bug was on old version. Explained the bug here: https://github.com/ManeraKai/simplytranslate-flutter-client/issues/57#issuecomment-924324692
Try it with the last artifact.

**Comment by Valdnet** [comment]
> Try it with the last artifact.

I have the latest [artifact](https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1259365210).

**Comment by ManeraKai** [comment]
Oh sorry, I thought you said when the **translation input** is empty. My bad.

**Comment by ManeraKai** [comment]
It's funny, but I can't find a clear clipboard button on my personal devices. If you have that button without restarting the device. Try it while you're in the app, and tell me if it's working fine: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1260837152

**Comment by ManeraKai** [comment]
Still not working.

**Comment by Valdnet** [comment]
> Still not working.

Ok. I am waiting for changes 😉.

**Comment by ManeraKai** [comment]
I think it's working now, hopefully: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1261563277

**Comment by Valdnet** [comment]
@ManeraKai Does not work properly. When the clipboard is empty, the "Paste" icon is still active.

**Comment by ManeraKai** [comment]
Upon restart it works. But live clipboard emptiness recognition doesn't work. Updated it now. I tried it and it works for me: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1261617633

**Comment by Valdnet** [comment]
@ManeraKai Still the "Paste" icon is active.
BTW: To clear the clipboard, did you try to restart your smartphone, for example?

**Comment by ManeraKai** [comment]
> BTW: To clear the clipboard, did you try to restart your smartphone, for example?

Yes, but after trying to clear it without restarting it. I found out that if I cleared my computers clipboard, it will clear it for the phone. For my personal physical device, restarting is the only way.

> @ManeraKai Still the "Paste" icon is active.

The last artifact?:

https://user-images.githubusercontent.com/40805353/134338961-c6ee79ff-bcae-4bd2-9de0-2c0a257bec6a.mp4

**Comment by Valdnet** [comment]
> The last artifact?:

Yes. The last [artifact](https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1261617633).

Screenshot with empty clipboard:

![obraz](https://user-images.githubusercontent.com/47037905/134340512-360c2652-a374-4409-80a0-20cd9100e042.png)

**Comment by ManeraKai** [comment]
If you try to restart the app. Does it stay active?

**Comment by Valdnet** [comment]
Yes. He is still active.

**Comment by ManeraKai** [comment]
Testing on a real device gives a different result. Fixed it and tested it on my real device. Worked for my real device. Hope it works for you too: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1265076180

**Comment by Valdnet** [comment]
Now it works fine 👍.

**Comment by Valdnet** [comment]
Currently reverted to the active "Paste" icon when clipboard is empty due to an issue encountered in issue #92.
