### ISSUE TITLE
Shrink settings window for your own instance

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#75]
The window for entering the address of your own instance should be slightly narrowed according to the screenshot:

![obraz](https://user-images.githubusercontent.com/47037905/134301679-c9d240bb-79f8-4ac2-ae99-2dc699ef4ebc.png)

**Comment by ManeraKai** [comment]
It's shrinked now. Whether should it be a popup or not will be discussed here: #76
