### ISSUE TITLE
Checking your own instance

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#76]
When you enter the address of your own instance (some false one) and tap on "Check", only the loading progress appears. After exiting and selecting "Custom" again from the menu, the progress bar continues to appear indefinitely.

1. Add button "Cancel" to be able to stop checking.
2. After exiting the window, the application should stop checking. After reselecting the window of setting your own instance, the "Check" button should appear.

![obraz](https://user-images.githubusercontent.com/47037905/134303914-381c54a5-89ab-421c-81c0-adf695fe6889.png)

**Comment by Valdnet** [comment]
You can enter the address, for example: `https: xxx.pl`. The main thing is that the address does not contain e.g.`:` or `//`.

**Comment by Valdnet** [comment]
This error also causes that if the instance is untested, it allows you to go to the translator, which makes it possible to translate without success.

**Comment by ManeraKai** [comment]
I'm not really satisfied with the pop for the custom instance. I'll make it as a widget in the page like before. It will make everything clearer for the user and me. Other popups won't be affected. Just the TextField input for the custom instance will be changed.

**Comment by ManeraKai** [comment]
What I mean:
<img width=360 src="https://user-images.githubusercontent.com/40805353/134462924-63e87e2e-b223-4e1d-86e5-c20310af8b78.png">
Don't mind that weird green border.

**Comment by Valdnet** [comment]
Hmmm ... I think it looks nice, but it doesn't match the whole application settings. Why can't these settings be in the pop-up window? Are there any problems? Many applications have pop-up windows. In the current storm structure, it's all settings.

@Aga-C  What do you think about it?

**Comment by ManeraKai** [comment]
> Why can't these settings be in the pop-up window? 

Just the custom TexfField input. Everything else is a popup.
<img width=360 src="https://user-images.githubusercontent.com/40805353/134464992-45710aed-98ea-4818-9314-d4c066de777b.png">
 
> Does button "X" close the instance settings?

This means that I should change the button. It's saying that does the instance pass the checkInstance function. Is it usable or not.

**Comment by ManeraKai** [comment]
Design will be improved. This was just to write the logic.

**Comment by Aga-C** [comment]
I prefer the old version where this setting was in popup.

**Comment by Valdnet** [comment]
In my opinion, it all looks a bit strange, but maybe that's just my observation. It's hard to confirm the idea as you can't test manually.

> I prefer the old version where this setting was in popup.

I'm for 👍.

**Comment by ManeraKai** [comment]
I'll run a Github Action and we'll see which one both of you prefer: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1264833971

**Comment by Aga-C** [comment]
I've tested it and still think that everything related to the instance should be in pop-ups.

**Comment by Valdnet** [comment]
I am also for having everything in a pop-up window. Now is the mix 😬.

**Comment by ManeraKai** [comment]
No problem.

**Comment by Valdnet** [comment]
"Update official list" can be given as a separate function in the instance settings. By clicking on this option the list would be updated.

Example:

- Instance
- Update official list
- Theme

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/issues/65#issuecomment-925562452

**Comment by ManeraKai** [comment]
> What do you think? How visually?

I liked it, here is how it looks on implementing:
<img width=360 src="https://user-images.githubusercontent.com/40805353/134581636-a11aa4ee-1840-4587-ad61-e4788623fdc3.png">

**Comment by Valdnet** [comment]
Very nice settings 🥇.

**Comment by Valdnet** [comment]
Is the "Custom" function complete?

Missing:

1. Self-check confirmations: success or error message.
2. List download receipts for "Update official list": download message or download error.
3. Text window borders as you type the instance address.

![obraz](https://user-images.githubusercontent.com/47037905/134628984-a669e23f-b5dd-4a84-b186-1cb366bedf9e.png)

Instance checking procedure:

1. Enter the address (border color without any names - gray).

![obraz](https://user-images.githubusercontent.com/47037905/134629409-2f4b579c-eea8-4e31-9a27-f1a5dc113691.png)

2. Address check successful (green window border - theme color).

![obraz](https://user-images.githubusercontent.com/47037905/134629712-ca0b05b0-e363-4305-818d-8bcf14bd00cb.png)

3. Address check failed (red window border).

![obraz](https://user-images.githubusercontent.com/47037905/134629781-12dc4490-bc89-42b4-8253-b98b14db6ed6.png)

**Comment by ManeraKai** [comment]
> Is the "Custom" function complete?

Working on it.

> List download receipts for "Update official list": download message or download error.

Got it.

>Text window borders as you type the instance address.

Maybe the fill color or the border color:

Btw the design that you took screenshots of is old. I'm making it a popup again.

**Comment by Valdnet** [comment]
> Maybe the fill color or the border color:

The color of the window border. It will be more aesthetically pleasing.
The red background is too much for the eyes 😬.

> Btw the design that you took screenshots of is old. I'm making it a popup again.

Cool 👍.

**Comment by ManeraKai** [comment]
The error is just now for borders.
Still didn't create a list download state yet. I'll work on it.

**Comment by ManeraKai** [comment]
Weirdly the updateList function was replaced with a checkInstance function. Fixed that. Added snackBars (the bottom notifications).

**Comment by ManeraKai** [comment]
GitHub Action: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1269083080
Will close the issue if you didn't encounter any problem.

**Comment by Valdnet** [comment]
Should be corrected:

1. When checking an instance, if I enter an HTTP address, e.g.: http://simplytranslate.org, the check is correct, but the translator does not translate. My guess is there must be HTTPS protocol, but the user may not know about it. The test must fail when checking the instance, or state that the protocol must be changed to HTTPS.

2. After changing the location of the smartphone horizontally while editing, entering your own instance, the editing window disappears.

![obraz](https://user-images.githubusercontent.com/47037905/134653877-2554f8cd-ef90-4747-8617-72b84123aba9.png)

**Comment by ManeraKai** [comment]
1. I'll take a look at this problem, because it redirects to the https version on my web browser.
2. I'll add a scroll widget.

**Comment by ManeraKai** [comment]
Fixed both of them: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1269562968

**Comment by Valdnet** [comment]
Tests passed 👍. It looks and works very well 😉.

I close the issue. If I notice anything else, I will open it again.
