### ISSUE TITLE
Typo in the F-Droid Description

### ISSUE THREAD

**Issue by metalune1** [ManeraKai/simplytranslate-flutter-client#77]
There is a typo in the F-Droid Description `Noramlly` instead of `Normally` in the first line

**Comment by ManeraKai** [comment]
It's in the F-Droid website. If you look at the file here in github: https://github.com/ManeraKai/simplytranslate-flutter-client/blob/main/fastlane/metadata/android/en-US/full_description.txt It will be corrected. Because we didn't add another release, it didn't get updated on F-Droids repo.

**Comment by metalune1** [comment]
ah I see, nevermind then :D
