### ISSUE TITLE
Text character count

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#79]
Steps:

1. Enter text.
2. Paste the text via the "Paste" icon.

Pasted text characters are not counted.

![obraz](https://user-images.githubusercontent.com/47037905/134331130-dc348190-e05f-4d43-9c0a-0c37e021a9ca.png)

Steps:

1. Enter your text.
2. Translate the text using the "Translate" button.
3. Replace the languages with "<->".

The number of text characters are not counted correctly. The number of characters remains from the previous text.

![obraz](https://user-images.githubusercontent.com/47037905/134331722-1a2b331e-25e7-4087-9fd2-5b6213f2378c.png)

**Comment by ManeraKai** [comment]
Fixed it.
