### ISSUE TITLE
Possibility to translate directly from other apps

### ISSUE THREAD

**Issue by Aga-C** [ManeraKai/simplytranslate-flutter-client#8]
Hi,

It would be nice to add an option to translate selected text in other apps directly via share button and/or from the menu under 3 dots (see screenshot).

![image](https://user-images.githubusercontent.com/85929121/133141667-e400928c-d098-4f23-a593-c55d8dd45854.png)

**Comment by Valdnet** [comment]
This feature will surely make it easier for users to translate and need to be added as soon as possible 😉.

**Comment by ManeraKai** [comment]
Update on this: I've managed to add a `Simply Translate` option to the text selection toolbar. Now I should receive that message from the system. Didn't find someone who did it in Flutter. Just in Java or Kotlin.  So, it may take sometime.

**Comment by ManeraKai** [comment]
I've added some native Kotlin code to the mix. That's why this feature won't be available in iOS. Swift code should be written for that.
