### ISSUE TITLE
Send >5000 characters by changing language

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#80]
Steps:

1. Enter a text of more than 5000 characters.
2. Change the languages using the "<->" button.

The text is sent for translation. The character counter remains unchanged.

![obraz](https://user-images.githubusercontent.com/47037905/134333378-1e6dae48-a0bc-4c21-bc2f-4dc2e38f8601.png)

**Comment by ManeraKai** [comment]
Fixed that, but I have a question. Why on earth should the text be translated and flipped and translated if we pressed the switch lang button. Why doesn't it just swap the langs and nothing else. Changing the text may not be the user's intention. The button's job is to swap languages. No one told it to touch the text. Google Translate just swaps the langs without touching the text.
What do you think @Valdnet?

**Comment by Valdnet** [comment]
> Why on earth should the text be translated and flipped and translated

That's because that's what google translate does 😉.

> Google Translate just swaps the langs without touching the text.

And here you are wrong. Google translator not only translates immediately when you change the language, but even translates when you change to another language not previously selected, and this is not what your application does. Not only that, goole translator translates directly when entering words, but it is known that the application would have to connect all the time, which is not needed for the user, and not even advisable for the application.

Here is an example of translation and reverse translation to clear your doubts, here I am giving an example of translation and reverse translation to clear your doubts.

- Your original text written in the previous comment:

`Fixed that, but I have a question. Why on earth should the text be translated and flipped and translated if we pressed the switch lang button. Why doesn't it just swap the langs and nothing else. Changing the text may not be the user's intention. The button's job is to swap languages. No one told it to touch the text. Google Translate just swaps the langs without touching the text.`

- Text translated into Polish:

`Naprawiłem to, ale mam pytanie. Dlaczego, u licha, tekst miałby być tłumaczony, odwracany i tłumaczony, jeśli nacisnęliśmy przycisk przełącznika języka. Dlaczego po prostu nie zamienia języka i nic więcej. Zmiana tekstu może nie być intencją użytkownika. Zadaniem przycisku jest zamiana języków. Nikt nie kazał jej dotykać tekstu. Tłumacz Google po prostu zamienia języki bez dotykania tekstu.`

- And the translation is reversed from Polish to English:

`I fixed it, but I have a question. Why on earth would the text be translated, flipped and translated if we pressed the language switch button. Why doesn't he just change the language and nothing else. Changing the text may not be your intention. The button's task is to change languages. Nobody told her to touch the text. Google Translate simply swaps languages without touching the text.`

Do you see the difference between the original text and the secondary text?

And that's what I was talking about. On single words, it may not matter, but when you put together sentences, this (magical) option allows you to choose the words and their arrangement (stylistics) so that the translated text is written almost perfectly and will be understood by any reading person.

Do you have any more questions?

**Comment by ManeraKai** [comment]
Google translate, in the web version, switches and translates. In the mobile version. It doesn't.

>And that's what I was talking about. On single words, it may not matter, but when you put together sentences, this (magical) option allows you to choose the words and their arrangement (stylistics) so that the translated text is written almost perfectly and will be understood by any reading person.

Interesting, now I've understood what that magical thing is.

If you wanted as a feature, No problem.

**Comment by Valdnet** [comment]
> In the mobile version. It doesn't.

I don't know about the mobile version because I don't use it.

That is why your application is created 😉.

> If you wanted as a feature, No problem.

Thank you.

**Comment by ManeraKai** [comment]
What should the app do though if he encountered a 5000+ document? Currently, it just switches langs without translating. What do you think it should do?

**Comment by Valdnet** [comment]
> Currently, it just switches langs without translating.

A - window with the text to be translated
B - window with translated text

1. Display the text to be translated in window A.
2. In window B it should be without text (blank).
3. Indicate the number of characters in red.

The user knows what's going on and can always edit the text to be translated.

**NOTE:** I have found an error. The translator does not translate over 500 characters. Somewhere in the conditions you lost the "0" sign.

**Comment by ManeraKai** [comment]
> Indicate the number of characters in red.

It's red automatically without pressing anything.

Should the langs be switched though?

>NOTE: I have found an error. The translator does not translate over 500 characters. Somewhere in the conditions you lost the "0" sign.

Sorry for that. Changed it.

**Comment by Valdnet** [comment]
> It's red automatically without pressing anything.

I guessed so, but preferred to add this information 😉.

> Should the langs be switched though?

I will describe how it is supposed to work so that there is no misunderstanding:

**A** - window with the text to be translated
**B** - window with translated text

Entering text, e.g. 5000 characters into window **A**.
Translate the text with the "Translate" button.
The text in the window is> 5000.
Change the languages with the "<->" button.
Copies text from window **B** -> **A**.
Window **B** is empty.
Information for the user via the counter icon.


The user is informed that the text is too long via the counter icon. He can always edit the text to be translated.

Second procedure for text >5000 entered by the user:

1. Entering text, e.g. 5001 characters into window **A**.
2. Translation lock by the "Translate" button.
3. The ability to change the language via the "<->" button.
4. Window **A** unchanged.
5. Window **B** is empty.

**Comment by Valdnet** [comment]
In the last test version it works correctly according to the procedures.

**Comment by ManeraKai** [comment]
Even if: A < 5000, B > 5000 ?

**Comment by Valdnet** [comment]
> Even if: A < 5000, B > 5000 ?

Yes. I will test a little. If there is no error, I will close the issue 😉.

**Comment by Valdnet** [comment]
Works correctly 👍. I close the issue.
