### ISSUE TITLE
Close list of languages

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#81]
Steps:

1. Expand the list of languages.
2. Hide keyboard with "down arrow".
3. Tap on the window for the translated text.

Language selection bar does not **hide automatically**.

![obraz](https://user-images.githubusercontent.com/47037905/134367579-89f7bb57-6dc1-4c37-9b80-49143e7ebedd.png)

 Same behavior for both lists. Also, tapping on the top banner of the application does not disable the language selection.

**Comment by ManeraKai** [comment]
Fixed it. Tapping on the AppBar or Anywhere else other than the tab-bar buttons will unfocus.
