### ISSUE TITLE
Invisible button "Translate" keyboard

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#85]
Steps:

1. Launch the application.
2. Paste the text using the "Paste" icon.

After pasting the text, the "Translate" button does not appear above the keyboard.

Additional information:

1. The "Translate" button appears only after tapping on the edit window or when typing text.
2. This only happens the first time you run the application.

![obraz](https://user-images.githubusercontent.com/47037905/134506542-218c75df-7a33-486d-b455-00d4a770223c.png)

**Comment by ManeraKai** [comment]
Fixed.
