### ISSUE TITLE
Completion of new version

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#86]
The completion of the new version of the application is near. Lots of new features and bugs have been fixed, the app has been given a new look and theme selection.

To-do list:

- [x] Tests
- [x] Appearance (Theme)
- [x] Application menu
- [x] Settings
- [x] About the application 
- [x] Translation

After all goals are achieved, I think the developer can release a new version of the application.

If there are any suggestions or concerns, please comment on this issue.

**Comment by ManeraKai** [comment]
The application menu is finished. You meant the little 3 dots top-right yes?

**Comment by Valdnet** [comment]
Not. I meant the settings. But it's good that you paid attention. I will add "Settings" to the list 😉.

**Comment by Valdnet** [comment]
The last corrections to the appearance of the application are at the end. A few bugs still need to be removed. But the developer may already be thinking about adding "About" 😉.

**Comment by Valdnet** [comment]
I would like the latest test version, please 😁.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1273942112

**Comment by Valdnet** [comment]
The application passes the tests correctly.

@ManeraKai is there anything you can do with #61 before a new version is released?

**Comment by ManeraKai** [comment]
I'm looking at it. Until now I've found a way to customize the TextSelectionToolbar, but for that you need almost 180 lines of code of.

**Comment by ManeraKai** [comment]
This was just customizing the color. The position is another thing. I'm trying to simplify the example that I got my hands on to start having conditions on position.

**Comment by Valdnet** [comment]
After careful analysis and removal of an unexpected bug, we had to leave issue #61 for repair after a new version was released.

The application has passed the tests 😁.

**Comment by ManeraKai** [comment]
There is one bug I found. I'll open an issue for it.

**Comment by ManeraKai** [comment]
Fixed it. We are ready!!!

**Comment by Valdnet** [comment]
> We are ready!!!

:v: :v: :v:
Release the app for use. We will see how many errors the users will find 😁.

**Comment by ManeraKai** [comment]
> We will see how many errors the users will find grin.

I fear that, but it's necessary.
btw: here #109 I have written a review and waiting for you.

**Comment by Valdnet** [comment]
> here #109 I have written a review and waiting for you.

I do not see. Are you sure?

**Comment by ManeraKai** [comment]
see the reviews part, you've requested a review, and I started one.

**Comment by Valdnet** [comment]
I do not see:

![obraz](https://user-images.githubusercontent.com/47037905/134860971-ba8e3fdb-5d23-4f9a-8653-60eb05cf144b.png)

**Comment by ManeraKai** [comment]
I started one but didn't submitted it for the public.

**Comment by Valdnet** [comment]
I have made changes 😉.

**Comment by ManeraKai** [comment]
So... I think I will create a release?

**Comment by Valdnet** [comment]
Of course. Let him go out into the world :grin:.

**Comment by ManeraKai** [comment]
Released it to the world. Now we'll wait for F-Droid to auto-compile it.

**Comment by Valdnet** [comment]
@ManeraKai @Aga-C A piece of good work.

**Comment by Valdnet** [comment]
The new version is out, please wait for it to appear on F-Droid.

So, I'm closing the issue.

**Comment by ManeraKai** [comment]
There are somethings that should be done manually: https://f-droid.org/en/docs/Update_Processing/

**Comment by Valdnet** [comment]
The new version is already in [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.simplytranslate.yml) 😁.

**Comment by Valdnet** [comment]
Something can't see the new version in F-Droid.

@ManeraKai Is it possible to put the apk file on github? Just like other repositories do. This will always speed up the release of a new version.

**Comment by ManeraKai** [comment]
I'm checking it day by day. F-Droid builds apps itself. Doesn't allow for compiled `.apk`s unless for some exceptions.
Also, it has signing keys. My keys will give warnings to users if I compiled a release `apk` and added it to releases.
They're a small team, I think we should wait a little bit. If it keeps being like this, I'll try and see the nightly build option.

**Comment by Valdnet** [comment]
There is a new version for F-Droid and there is a bug 😬.

**Comment by ManeraKai** [comment]
A bug?
