### ISSUE TITLE
Setting default language for translation

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#89]
When selecting a text for translation from another application, e.g. a web browser, the problem arises that if the translator has the languages set, eg French <-> German, and the text is in English and I want to translate it into Polish, it requires re-translation.

The suggestion is that in the application settings you can set the default language, e.g. Polish, to which you want to translate. After selecting the translator "Simply Translate", the application would automatically change the languages to: Autodetect <-> Polish. If the user changed to the default language e.g. Arabic, the translator would automatically change to Autodetect <-> Arabic.

I think it would make the application easier to use.

**Comment by Valdnet** [comment]
An example of setting the default language for translation in the application settings:

![obraz](https://user-images.githubusercontent.com/47037905/134581323-dd2602f8-7610-46be-b6e6-be15fe4835c0.png)

**Comment by ManeraKai** [comment]
You mean the default share language?

**Comment by ManeraKai** [comment]
I mean there should be an explanation that this setting is related to the share feature. Until now, this is the only thing this setting is used for.

**Comment by Valdnet** [comment]
> I mean there should be an explanation that this setting is related to the share feature.

A very good point. I'll change the example in a moment 😉.

**Comment by ManeraKai** [comment]
Has been added. The language search isn't the prettiest on the planet. It can be improved, but the logic is done, hopefully.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1270492800

**Comment by Valdnet** [comment]
Errors:
**1**. After setting the default language, eg Polish, after exiting the settings, the Polish language is automatically set for translations.

Steps:

1. Set the language to e.g. Polish.
2. Exit the settings.

![obraz](https://user-images.githubusercontent.com/47037905/134708273-f53d2e71-9297-45db-ba5b-ef69a0332a20.png)

![obraz](https://user-images.githubusercontent.com/47037905/134708177-7912c79b-e596-4d98-84a5-ac91b981ed13.png)

**Correct behavior:**

The default language should not be automatically set for translations. We get the result, for example: Polish <-> Polish.

**2**. The language set, for example: Polish, after re-entering the settings, it does not remember the language set. It returns to Arabic.

Steps:

1. Set the language to e.g. Polish.
2. Exit the settings.
3. Enter the settings again.

![obraz](https://user-images.githubusercontent.com/47037905/134708824-d00313be-4ee6-4590-a2c9-6dd73f3605aa.png)

![obraz](https://user-images.githubusercontent.com/47037905/134708921-ff90321b-9be3-40d8-bbee-bd8001619f5c.png)

**Correct behavior:**

Default language setting is remembered.

**3**. After setting the default language, e.g. Polish, translates the text into Arabic from the shared application.

![obraz](https://user-images.githubusercontent.com/47037905/134709672-e17b6dba-919a-4746-adc6-a6a2458ee0c4.png)

![obraz](https://user-images.githubusercontent.com/47037905/134709809-e20f284f-c4bb-46ca-8ea8-d4c5f0678e7e.png)

**Correct behavior:**

After sharing text from another application, the languages should be set to: Autoselect <-> Polish.
The translation should be for the Polish language.

**Comment by ManeraKai** [comment]
1. I've encountered this issue, but happened just once. I think you've pressed the language from the options instead of pressing enter.
2. Fixed by fixing the first one.
3. Also Fixed by fixing the first one.

**Comment by Valdnet** [comment]
> I've encountered this issue, but happened just once. I think you've pressed the language from the options instead of pressing enter.

Yes. I chose the language from the list. Choice should work that way too 😁.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1270701311

**Comment by Valdnet** [comment]
1. After re-entering, a list with language selection is displayed. The list should be displayed only after clicking on the window.

![obraz](https://user-images.githubusercontent.com/47037905/134716316-6e69814d-bf70-4a24-8b95-80a4af0e38a5.png)

2. Does not change the languages in the windows to Autodetect <-> Polish.

![obraz](https://user-images.githubusercontent.com/47037905/134716611-c5653434-afff-4b43-9f0d-3cdbb3181b82.png)

**Comment by ManeraKai** [comment]
1. If you clicked on the TextField, it will display the list. I've made it to auto-focus when the dialog pops up. It auto focuses but doesn't do the other things and one of them is displaying the list. I'll try to fix that.
2. They shouldn't be changed. The setting is for the share feature, not the usual translation.

**Comment by Valdnet** [comment]
> They shouldn't be changed. The setting is for the share feature, not the usual translation.

Hmmm. It looks a bit strange, but maybe you're right 😉. We will see in the tests how it turns out 😁.

**Comment by Valdnet** [comment]
The choice of the default language should be done in the same way as for the choice of the translation languages.

Procedure:

1. Tap on default language settings - "Default share to-language".
2. A window with the set language should appear.

No expanded list:

![obraz](https://user-images.githubusercontent.com/47037905/134741157-1a86c8f3-2649-44f2-b75e-f85f91ec2a09.png)

3. Tap on the language selection window.

The list with the languages is shown:

![obraz](https://user-images.githubusercontent.com/47037905/134740566-5c61d7ef-9d07-4537-a593-c943b2dfb9ac.png)

4. Language selection.
The list with the selection window closes.

**Comment by ManeraKai** [comment]
It was like that before. Reverted it back.

**Comment by Valdnet** [comment]
Previously, this was the case with the tap in "Default share to-languaguage".

￼

And it should be like this:

￼

 The point is, once the popup shows up, it shouldn't automatically expand the language list or the selected language. Only after tapping on the language window is the list of languages ​​drawn up. As it is for the choice of languages ​​for a translator.

**Comment by Valdnet** [comment]
One more thing needs to be improved. The first time you set it, the default language should appear in the window so that the user knows.

![obraz](https://user-images.githubusercontent.com/47037905/134760324-0ea25e12-1d18-4abc-b8f2-b032c8524913.png)

Currently it is like this:

![obraz](https://user-images.githubusercontent.com/47037905/134760393-1cf65885-b9d9-4d86-bcf5-04c2b92bfb5c.png)

Because the language is also visible to the user in the settings:

![obraz](https://user-images.githubusercontent.com/47037905/134760448-de0066f7-68ed-4aba-8ec4-0b43701d3b94.png)

**Comment by ManeraKai** [comment]
> Do the languages displayed in the settings need to be re-translated?

I took care of this. They're translated now.

**Comment by ManeraKai** [comment]
Won't appear until the user presses the TextField. will show the whole list. Fresh startup of the app will default to Arabic. Will be shown in the TextField and in the settings subText.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1272712142

**Comment by Valdnet** [comment]
In this case, the fixed text "Select language" must be entered for the first commissioning. The empty window looks a bit strange. The user may be a little confused.

![obraz](https://user-images.githubusercontent.com/47037905/134781186-85256db5-5205-484a-a4d3-39b1bc19fc13.png)

Although I would prefer the language name "Arabic" 😁.

**Comment by ManeraKai** [comment]
> The empty window looks a bit strange.

I did change it.

> Although I would prefer the language name "Arabic" grin.

Me too, that is what was implemented.

I downloaded the last artifact and checked. It really is translated.

**Comment by Valdnet** [comment]
> I downloaded the last artifact and checked. It really is translated.

But in the latest test version it still displays in English.
Are you sure it gets from text strings from `selectLanguagesMap`?

**Comment by ManeraKai** [comment]
It doesn't. It gets it from a variable called `toLanguageShareDefault`.

**Comment by ManeraKai** [comment]
It's the same value that you typed in the TextField. If it's angelize then it will be angelize. Values that are shared with servers use the `selectLanguagesMap`. They take this gibberish translation and find the corresponding English name. Send those English names to the servers because they just speak English.

**Comment by Valdnet** [comment]
Hmmm ... Check if your languages are translated in the settings 😉.

**Comment by ManeraKai** [comment]
I checked it in polish.

**Comment by Valdnet** [comment]
> I checked it in polish.

Well. When there is a new test version, I will test it again 😉.

**Comment by Valdnet** [comment]
Cool. There is a translation of the set language 👍 . Only the text string goes out of the window.

![obraz](https://user-images.githubusercontent.com/47037905/134785151-85cdbb5e-6f53-41f5-b465-3a5bb0a17583.png)

**Comment by Valdnet** [comment]
Automatic translation cancellation for sharing. Same as for issue #99 😁.

**Comment by ManeraKai** [comment]
<img src="https://st6.io/static/c0e2d815e6528c2c541a77c421129f48/c1b63/but-why.png">

**Comment by ManeraKai** [comment]
Fixed it but referenced in that issue.

**Comment by ManeraKai** [comment]
I think this issue should be closed now @Valdnet.

**Comment by Valdnet** [comment]
After many torments, I am happy to close the issue 😁. Many thanks to @ManeraKai 🥇.

**Comment by ManeraKai** [comment]
Hoping the same for the Paste button one day.
