### ISSUE TITLE
Continuous translation progress

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#94]
During translation, if the application is unable to download the translation for some reason, the translation progress continues.
There is nothing the user can do (translate again). Only shutting down the application and restarting it.

I suggest you either set a time limit to connect and download the translation, after which the application will indicate an error, or the "Cancel" button to abort the process.

![obraz](https://user-images.githubusercontent.com/47037905/134669325-a526575d-c003-4680-a35f-d8d05a7fc5e2.png)

![obraz](https://user-images.githubusercontent.com/47037905/134669437-0cb1f0a0-e3a8-4ff6-92b1-91a718f87bd9.png)

**Comment by ManeraKai** [comment]
I prefer the cancel button. Some users have a slow internet and I can't estimate that.

**Comment by Valdnet** [comment]
I also think the "Cancel" button will be better 😉.

**Comment by Valdnet** [comment]
You should change the font color for "Cancel" in a light theme 😉.

![obraz](https://user-images.githubusercontent.com/47037905/134684518-b6a03979-3794-4dae-af88-2bf6d2ab5ff8.png)

**Comment by ManeraKai** [comment]
Fixed that.

**Comment by Valdnet** [comment]
For testing, I suggest that the translation progress bar be moved above the "Cancel" text string (see screenshot).

Translation progress can be shown as a percentage or sweep as it was (as it was).

![obraz](https://user-images.githubusercontent.com/47037905/134742889-533ffb20-1185-4596-b083-e3b4b89fcff2.png)

Percentage indication:

![obraz](https://user-images.githubusercontent.com/47037905/134743328-ec004276-8c16-4ac5-8a0c-5467a3d588d7.png)
![obraz](https://user-images.githubusercontent.com/47037905/134743349-d9bff128-c719-4075-82f9-1eea0212a069.png)
![obraz](https://user-images.githubusercontent.com/47037905/134743377-9cf882ac-eb48-4cc8-9c61-979b006a09c4.png)

Sweep indication:

![obraz](https://user-images.githubusercontent.com/47037905/134743581-0263f58b-cb12-47bb-aaac-7f56689e5c07.png)
![obraz](https://user-images.githubusercontent.com/47037905/134743731-dae8486f-8594-4b81-821e-f07a49c78280.png)
![obraz](https://user-images.githubusercontent.com/47037905/134743650-b3095c05-800f-4d16-8226-93f568e2aa65.png)

**Comment by ManeraKai** [comment]
Changed it.
