### ISSUE TITLE
Add text strings for translation

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#95]
The following strings should be added to the translation files.

https://github.com/ManeraKai/simplytranslate-flutter-client/blob/c7d023f7b1eec6f4e4a0340245a5c87a996d4161/lib/screens/settings/widgets/update_list.dart#L102

https://github.com/ManeraKai/simplytranslate-flutter-client/blob/c7d023f7b1eec6f4e4a0340245a5c87a996d4161/lib/screens/settings/widgets/update_list.dart#L98

`Updated Successfully` should be changed to `Updated successfully`

**Comment by Valdnet** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/blob/624fd990b1d2f55f0a412d8a2eb4203087b27be5/lib/google/widgets/translation_input/widgets/paste_button.dart#L105

**Comment by Valdnet** [comment]
@Aga-C Would you like to take care of it?

**Comment by ManeraKai** [comment]
I think this issue should be closed @Valdnet?

**Comment by ManeraKai** [comment]
Translated Arabic.
