### ISSUE TITLE
Information about empty clipboard

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#96]
New idea to replace issues of #74 and #92.

If the clipboard is empty, after pressing the "Paste" icon for the text to be translated, the following message should appear: "Clipboard is empty". The user will know why the text was not pasted.
Just like copying text. The user is informed that they have been copied to the clipboard.

The current behavior is a bit strange behavior of the application when clicking on the "Paste" icon and taking no action. The user may think that this is some kind of application bug.

Procedure:

1. Pressing the "Paste" icon.
2. The application checks that the clipboard is not empty.
3. If it contains text, it pastes into the text edit window.
4. If it is empty, it informs the user about it.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1271017918

**Comment by Valdnet** [comment]
No message when clipboard is empty.

**Comment by ManeraKai** [comment]
sorry.

**Comment by Valdnet** [comment]
Works correctly 👍.
