### ISSUE TITLE
Double error message and connecting to internet

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#98]
- Steps:

1. Launch the application.
2. Turn off your internet connection.
3. Tap the language change button `<->`.

Duplicate "No internet connection" message appears.

![obraz](https://user-images.githubusercontent.com/47037905/134781751-667d3bec-abae-4fa4-8f37-d29d53f06926.png)

Duplicate "Check instance" message appears.

![obraz](https://user-images.githubusercontent.com/47037905/134784012-41fa0370-a3e4-4dc8-881c-7bd9a390c3a9.png)

- Steps:

1. Launch the application (empty edit field).
2. Tap the language change button `<->`.

When changing languages via the `<->` button for the text edit field, when it is **empty**, the application should not connect to the Internet. After big changes to the application, this is unnecessary.

![obraz](https://user-images.githubusercontent.com/47037905/134781908-aef901a9-2f01-4b66-a243-5a8c7810d6a1.png)

**Comment by ManeraKai** [comment]
Fixed both issues.
1.One alert will pop if no internet.
2. Will just switch langs.

**Comment by Valdnet** [comment]
> 1.One alert will pop if no internet.

And did you also fix for the "Check instance" alert?

**Comment by ManeraKai** [comment]
Test it now. yes works also for "Check instance".
