### ISSUE TITLE
Automatic cancellation of translation after an alert

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#99]
After "No internet connection" and "Check instance" messages appear, automatic termination of translation should occur (interruption of connection with the instance).

![obraz](https://user-images.githubusercontent.com/47037905/134785318-c31f2197-b5c5-4233-b872-82558e6e05ba.png)

**Comment by ManeraKai** [comment]
What is wrong?

**Comment by Valdnet** [comment]
Steps:

1. Launch the application.
2. Turn off your internet connection or make your instances inactive of your own.
3. Enter the text to translate.
4. Tap the "Translate" button.
5. Tap the "OK" button.

After the alert, it should automatically stop the progress of connecting to the instance (stop translating).

Currently, the user has to tap the "Cancel" button himself.

**Comment by ManeraKai** [comment]
Trying it with the keyboard button results in a total crash.

**Comment by Valdnet** [comment]
And for changing the translation languages too?
